// Auto-generated by generate_hdl_weights.py
// Model: tinyissimo_ptq_full_integer_quant.tflite
// Date:  2026-04-07 17:27:32
// DO NOT EDIT — regenerate from the TFLite model.
//
// C++ mirror of hardware/weights/hdl/layer_config.svh.
// Used by the HLS tinyissimo_layer_top function to walk all 17 layers.

#pragma once
#include <ap_int.h>
#include <cstdint>

constexpr int NUM_LAYERS    = 17;
constexpr int C_PARALLEL    = 16;
constexpr int ACT_LUT_DEPTH = 4352;

enum LayerType : uint8_t {
    LT_CONV3      = 0,
    LT_CONV3_POOL = 1,
    LT_CONV1      = 2,
    LT_CONV1_LIN  = 3,
};

struct LayerCfg {
    uint8_t  layer_type;
    uint16_t h_in;
    uint16_t w_in;
    uint16_t cin;
    uint16_t cout;
    uint8_t  cin_grp;
    uint16_t wt_base;
    uint16_t qp_base;
    int8_t   zp_in;
    int8_t   zp_out;
    uint8_t  pp_buf_sel;
    uint16_t pp_rd_offset;
    uint16_t pp_wr_offset;
    // Derived fields (for HLS convenience):
    uint8_t  use_silu;
    uint8_t  use_maxpool;
    uint8_t  kh;
    uint8_t  kw;
    uint8_t  pad_h;
    uint8_t  pad_w;
};

constexpr LayerCfg LAYER_CFG[NUM_LAYERS] = {
    /*  0 */ { LT_CONV3_POOL ,  256,  256,    3,   16,  1, 0x0000, 0x000,  -128,     3, 0,   0,   0, 1, 1, 3, 3, 1, 1 },
    /*  1 */ { LT_CONV3      ,  128,  128,   16,   16,  1, 0x0090, 0x010,  -126,    73, 1,   0,   0, 1, 0, 3, 3, 1, 1 },
    /*  2 */ { LT_CONV3_POOL ,  128,  128,   16,   16,  1, 0x0120, 0x020,  -123,    24, 0,   0,   0, 1, 1, 3, 3, 1, 1 },
    /*  3 */ { LT_CONV3      ,   64,   64,   16,   32,  1, 0x01b0, 0x030,  -122,    22, 1,   0,   0, 1, 0, 3, 3, 1, 1 },
    /*  4 */ { LT_CONV3_POOL ,   64,   64,   32,   32,  2, 0x02d0, 0x050,  -119,    10, 0,   0,   0, 1, 1, 3, 3, 1, 1 },
    /*  5 */ { LT_CONV3      ,   32,   32,   32,   64,  2, 0x0510, 0x070,  -117,    11, 1,   0,   0, 1, 0, 3, 3, 1, 1 },
    /*  6 */ { LT_CONV3_POOL ,   32,   32,   64,   64,  4, 0x0990, 0x0b0,  -117,    18, 0,   0,   0, 1, 1, 3, 3, 1, 1 },
    /*  7 */ { LT_CONV3      ,   16,   16,   64,   64,  4, 0x1290, 0x0f0,  -115,    -7, 1,   0,   0, 1, 0, 3, 3, 1, 1 },
    /*  8 */ { LT_CONV3_POOL ,   16,   16,   64,  128,  4, 0x1b90, 0x130,  -119,    14, 0,   0,   0, 1, 1, 3, 3, 1, 1 },
    /*  9 */ { LT_CONV3      ,    8,    8,  128,  128,  8, 0x2d90, 0x1b0,  -118,    -2, 1,   0,   0, 1, 0, 3, 3, 1, 1 },
    /* 10 */ { LT_CONV1      ,    8,    8,  128,   24,  8, 0x5190, 0x230,  -120,    11, 0,   0,   0, 1, 0, 1, 1, 0, 0 },
    /* 11 */ { LT_CONV3      ,    8,    8,   24,   64,  2, 0x5250, 0x248,  -115,     3, 1,   0, 256, 1, 0, 3, 3, 1, 1 },
    /* 12 */ { LT_CONV3      ,    8,    8,   64,   64,  4, 0x56d0, 0x288,  -119,   -11, 0, 256, 256, 1, 0, 3, 3, 1, 1 },
    /* 13 */ { LT_CONV1_LIN  ,    8,    8,   64,   64,  4, 0x5fd0, 0x2c8,  -122,    10, 1, 256, 256, 0, 0, 1, 1, 0, 0 },
    /* 14 */ { LT_CONV3      ,    8,    8,   24,   24,  2, 0x60d0, 0x308,  -115,     7, 1,   0, 512, 1, 0, 3, 3, 1, 1 },
    /* 15 */ { LT_CONV3      ,    8,    8,   24,   24,  2, 0x6280, 0x320,  -112,    26, 0, 512, 512, 1, 0, 3, 3, 1, 1 },
    /* 16 */ { LT_CONV1_LIN  ,    8,    8,   24,    3,  2, 0x6430, 0x338,  -117,    10, 1, 512, 512, 0, 0, 1, 1, 0, 0 }
};
