"""Lanczos 6-tap/64-phase coefficient table and phase computation for VPSS.

The VPSS polyphase scaler uses a 2D filter bank indexed by [phase][tap].
Each coefficient is S4.11 fixed-point (1 sign + 4 integer + 11 fractional bits),
stored as a 16-bit signed integer.

The phase of each output pixel determines which set of 6 coefficients to use.
Phases are computed based on the scaling ratio and stored in the H-Scaler's
phase RAM.

Reference: PG231 v2.3, Chapter 4 "Polyphase Scaling" and "Filter Coefficients"
"""

import math

# ---------------------------------------------------------------------------
# Lanczos-3 coefficient table: 64 phases × 6 taps
# ---------------------------------------------------------------------------
#
# Each phase p (0..63) represents a fractional offset of p/64 between input
# pixels.  Phase 0 = output pixel aligned with input pixel (center tap only).
#
# Generated by _generate_lanczos_table(6, 64) below, then verified to sum
# to 2048 (= 1.0 in S4.11) for every phase.


def _lanczos_kernel(x: float, a: int = 3) -> float:
    """Lanczos-a kernel: sinc(x) * sinc(x/a) for |x| < a, else 0."""
    if abs(x) < 1e-10:
        return 1.0
    if abs(x) >= a:
        return 0.0
    px = math.pi * x
    return (math.sin(px) / px) * (math.sin(px / a) / (px / a))


def _generate_lanczos_table(num_taps: int = 6, num_phases: int = 64) -> list:
    """Generate a Lanczos coefficient table as S4.11 fixed-point integers.

    Returns:
        List of `num_phases` lists, each containing `num_taps` ints in
        S4.11 format (range -2^15 .. 2^15-1).
    """
    half = num_taps / 2.0  # 3.0 for 6-tap
    table = []
    for phase in range(num_phases):
        frac = phase / num_phases  # fractional offset [0, 1)
        raw = []
        for tap in range(num_taps):
            # x is the distance from the output pixel to this tap's input pixel.
            # Tap 0 is the leftmost; for 6-tap, center is between tap 2 and 3.
            x = tap - (half - 1.0) - frac  # e.g. tap0: -2.0 - frac
            raw.append(_lanczos_kernel(x, a=num_taps // 2))

        # Normalize so coefficients sum to 1.0
        total = sum(raw)
        if total > 0:
            raw = [v / total for v in raw]

        # Convert to S4.11: multiply by 2048, round
        s411 = [round(v * 2048) for v in raw]

        # Force the sum to exactly 2048 by adjusting the largest coefficient
        residual = 2048 - sum(s411)
        if residual != 0:
            max_idx = max(range(num_taps), key=lambda i: abs(s411[i]))
            s411[max_idx] += residual

        # Clamp to 16-bit signed range
        s411 = [max(-32768, min(32767, v)) for v in s411]

        table.append(s411)

    return table


# Pre-computed table — avoids runtime math on the board.
LANCZOS_6TAP_64PHASE = _generate_lanczos_table(6, 64)


def pack_coefficients(table: list, num_taps: int, num_phases: int) -> list:
    """Pack a coefficient table into 32-bit words for writing to the scaler.

    PG231: Two S4.11 coefficients per 32-bit word.
        bits [15:0]  = coeff[2n]     (lower half)
        bits [31:16] = coeff[2n+1]   (upper half)

    The memory layout is: phase 0 tap 0..5, phase 1 tap 0..5, ...
    With 6 taps, each phase occupies 3 words (6 coefficients / 2 per word).

    Args:
        table: List of `num_phases` lists of `num_taps` S4.11 integers.
        num_taps: Number of filter taps (must be even).
        num_phases: Number of phases.

    Returns:
        List of (byte_offset, word_value) tuples for writing to coefficient RAM.
    """
    words = []
    word_idx = 0
    for phase in range(num_phases):
        for tap in range(0, num_taps, 2):
            lo = table[phase][tap] & 0xFFFF
            hi = table[phase][tap + 1] & 0xFFFF
            word = (hi << 16) | lo
            words.append((word_idx * 4, word))
            word_idx += 1
    return words


def calculate_phases(width_in: int, width_out: int, num_phases: int = 64) -> list:
    """Calculate the phase index for each output pixel.

    Port of Xilinx CalculatePhases() from xv_hscaler_l2.c.
    For each output pixel, the phase determines which set of filter
    coefficients to apply based on the sub-pixel position.

    Args:
        width_in: Input width in pixels.
        width_out: Output width in pixels.
        num_phases: Number of filter phases (64).

    Returns:
        List of `width_out` phase indices (0..num_phases-1), each 9-bit.
    """
    phases = []
    for x in range(width_out):
        # The fractional position of this output pixel in input space,
        # scaled by num_phases.  The integer part selects the input pixel,
        # the fractional part (mod num_phases) selects the phase.
        pos = (x * width_in * num_phases) // width_out
        phase = pos % num_phases
        phases.append(phase & 0x1FF)  # 9-bit
    return phases


def pack_phases(phases: list) -> list:
    """Pack phase indices into 32-bit words for H-Scaler phase RAM.

    PG231: Two 9-bit phase values per 32-bit word.
        bits [8:0]   = phase[2n]
        bits [24:16] = phase[2n+1]

    Args:
        phases: List of 9-bit phase indices.

    Returns:
        List of (byte_offset, word_value) tuples for writing to phase RAM.
    """
    words = []
    # Pad to even length
    padded = list(phases)
    if len(padded) % 2:
        padded.append(0)

    for i in range(0, len(padded), 2):
        lo = padded[i] & 0x1FF
        hi = padded[i + 1] & 0x1FF
        word = (hi << 16) | lo
        words.append((i * 2, word))  # 2 entries per 4-byte word => stride 4
    return words
