-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tinyissimo_layer_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fmap_a_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    fmap_a_EN_A : OUT STD_LOGIC;
    fmap_a_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    fmap_a_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    fmap_a_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    fmap_a_Clk_A : OUT STD_LOGIC;
    fmap_a_Rst_A : OUT STD_LOGIC;
    fmap_a_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    fmap_a_EN_B : OUT STD_LOGIC;
    fmap_a_WEN_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    fmap_a_Din_B : OUT STD_LOGIC_VECTOR (127 downto 0);
    fmap_a_Dout_B : IN STD_LOGIC_VECTOR (127 downto 0);
    fmap_a_Clk_B : OUT STD_LOGIC;
    fmap_a_Rst_B : OUT STD_LOGIC;
    fmap_b_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    fmap_b_EN_A : OUT STD_LOGIC;
    fmap_b_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    fmap_b_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    fmap_b_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    fmap_b_Clk_A : OUT STD_LOGIC;
    fmap_b_Rst_A : OUT STD_LOGIC;
    fmap_b_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
    fmap_b_EN_B : OUT STD_LOGIC;
    fmap_b_WEN_B : OUT STD_LOGIC_VECTOR (15 downto 0);
    fmap_b_Din_B : OUT STD_LOGIC_VECTOR (127 downto 0);
    fmap_b_Dout_B : IN STD_LOGIC_VECTOR (127 downto 0);
    fmap_b_Clk_B : OUT STD_LOGIC;
    fmap_b_Rst_B : OUT STD_LOGIC;
    wt_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    wt_mem_EN_A : OUT STD_LOGIC;
    wt_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    wt_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    wt_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    wt_mem_Clk_A : OUT STD_LOGIC;
    wt_mem_Rst_A : OUT STD_LOGIC;
    qp_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    qp_mem_EN_A : OUT STD_LOGIC;
    qp_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    qp_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    qp_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    qp_mem_Clk_A : OUT STD_LOGIC;
    qp_mem_Rst_A : OUT STD_LOGIC;
    silu_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    silu_mem_EN_A : OUT STD_LOGIC;
    silu_mem_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
    silu_mem_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
    silu_mem_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0);
    silu_mem_Clk_A : OUT STD_LOGIC;
    silu_mem_Rst_A : OUT STD_LOGIC;
    curr_layer_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    curr_layer_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of tinyissimo_layer_top is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "tinyissimo_layer_top_tinyissimo_layer_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.223000,HLS_SYN_LAT=82852136,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=22241,HLS_SYN_LUT=61996,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal LAYER_CFG_h_in_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_h_in_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal LAYER_CFG_w_in_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_w_in_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal LAYER_CFG_cin_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_cin_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LAYER_CFG_cout_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_cout_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LAYER_CFG_wt_base_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_wt_base_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal LAYER_CFG_qp_base_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_qp_base_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal LAYER_CFG_zp_in_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_zp_in_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LAYER_CFG_zp_out_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_zp_out_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LAYER_CFG_pp_buf_sel_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_pp_buf_sel_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal LAYER_CFG_pp_rd_offset_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_pp_rd_offset_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal LAYER_CFG_pp_wr_offset_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_pp_wr_offset_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal LAYER_CFG_use_silu_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_use_silu_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal LAYER_CFG_use_maxpool_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_use_maxpool_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal LAYER_CFG_kh_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_kh_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LAYER_CFG_kw_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_kw_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LAYER_CFG_pad_h_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_pad_h_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal LAYER_CFG_pad_w_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal LAYER_CFG_pad_w_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln42_fu_387_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln42_reg_442 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cfg_h_in_reg_532 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal cfg_w_in_reg_537 : STD_LOGIC_VECTOR (8 downto 0);
    signal cfg_cin_reg_542 : STD_LOGIC_VECTOR (7 downto 0);
    signal cfg_cout_reg_547 : STD_LOGIC_VECTOR (7 downto 0);
    signal cfg_wt_base_reg_552 : STD_LOGIC_VECTOR (14 downto 0);
    signal cfg_qp_base_reg_557 : STD_LOGIC_VECTOR (9 downto 0);
    signal cfg_zp_in_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal cfg_zp_out_reg_567 : STD_LOGIC_VECTOR (7 downto 0);
    signal LAYER_CFG_pp_buf_sel_q0_local : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_pp_buf_sel_reg_572 : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_pp_rd_offset_reg_576 : STD_LOGIC_VECTOR (9 downto 0);
    signal cfg_pp_wr_offset_reg_581 : STD_LOGIC_VECTOR (9 downto 0);
    signal cfg_use_silu_reg_586 : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_use_maxpool_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_kh_reg_596 : STD_LOGIC_VECTOR (1 downto 0);
    signal cfg_kw_reg_601 : STD_LOGIC_VECTOR (1 downto 0);
    signal cfg_pad_h_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal cfg_pad_w_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal packed_rgb_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal packed_rgb_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tinyissimo_layer_fu_323_ap_start : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_ap_done : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_ap_idle : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_ap_ready : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_fmap_a_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_EN_A : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_fmap_a_WEN_A : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_Din_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_Dout_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_Addr_B : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_EN_B : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_fmap_a_WEN_B : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_Din_B : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_a_Dout_B : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_b_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_b_EN_A : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_fmap_b_WEN_A : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tinyissimo_layer_fu_323_fmap_b_Din_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_wt_mem_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_wt_mem_EN_A : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_wt_mem_WEN_A : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tinyissimo_layer_fu_323_wt_mem_Din_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_qp_mem_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_qp_mem_EN_A : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_qp_mem_WEN_A : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tinyissimo_layer_fu_323_qp_mem_Din_A : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_tinyissimo_layer_fu_323_silu_mem_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_tinyissimo_layer_fu_323_silu_mem_EN_A : STD_LOGIC;
    signal grp_tinyissimo_layer_fu_323_silu_mem_WEN_A : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tinyissimo_layer_fu_323_silu_mem_Din_A : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tinyissimo_layer_fu_323_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln42_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln42_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal L_fu_90 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal zext_ln46_fu_414_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal LAYER_CFG_h_in_ce0_local : STD_LOGIC;
    signal LAYER_CFG_w_in_ce0_local : STD_LOGIC;
    signal LAYER_CFG_cin_ce0_local : STD_LOGIC;
    signal LAYER_CFG_cout_ce0_local : STD_LOGIC;
    signal LAYER_CFG_wt_base_ce0_local : STD_LOGIC;
    signal LAYER_CFG_qp_base_ce0_local : STD_LOGIC;
    signal LAYER_CFG_zp_in_ce0_local : STD_LOGIC;
    signal LAYER_CFG_zp_out_ce0_local : STD_LOGIC;
    signal LAYER_CFG_pp_buf_sel_ce0_local : STD_LOGIC;
    signal LAYER_CFG_pp_rd_offset_ce0_local : STD_LOGIC;
    signal LAYER_CFG_pp_wr_offset_ce0_local : STD_LOGIC;
    signal LAYER_CFG_use_silu_ce0_local : STD_LOGIC;
    signal LAYER_CFG_use_maxpool_ce0_local : STD_LOGIC;
    signal LAYER_CFG_kh_ce0_local : STD_LOGIC;
    signal LAYER_CFG_kw_ce0_local : STD_LOGIC;
    signal LAYER_CFG_pad_h_ce0_local : STD_LOGIC;
    signal LAYER_CFG_pad_w_ce0_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component tinyissimo_layer_top_tinyissimo_layer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_h : IN STD_LOGIC_VECTOR (8 downto 0);
        in_w : IN STD_LOGIC_VECTOR (8 downto 0);
        in_c : IN STD_LOGIC_VECTOR (7 downto 0);
        out_c : IN STD_LOGIC_VECTOR (7 downto 0);
        kh : IN STD_LOGIC_VECTOR (1 downto 0);
        kw : IN STD_LOGIC_VECTOR (1 downto 0);
        pad_h : IN STD_LOGIC_VECTOR (0 downto 0);
        pad_w : IN STD_LOGIC_VECTOR (0 downto 0);
        use_maxpool : IN STD_LOGIC_VECTOR (0 downto 0);
        use_silu : IN STD_LOGIC_VECTOR (0 downto 0);
        layer_idx : IN STD_LOGIC_VECTOR (4 downto 0);
        zp_in : IN STD_LOGIC_VECTOR (7 downto 0);
        zp_out : IN STD_LOGIC_VECTOR (7 downto 0);
        wt_base : IN STD_LOGIC_VECTOR (14 downto 0);
        qp_base : IN STD_LOGIC_VECTOR (9 downto 0);
        fmap_rd_offset : IN STD_LOGIC_VECTOR (9 downto 0);
        fmap_wr_offset : IN STD_LOGIC_VECTOR (9 downto 0);
        packed_rgb_input : IN STD_LOGIC_VECTOR (0 downto 0);
        fmap_a_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        fmap_a_EN_A : OUT STD_LOGIC;
        fmap_a_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        fmap_a_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
        fmap_a_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
        fmap_a_Addr_B : OUT STD_LOGIC_VECTOR (31 downto 0);
        fmap_a_EN_B : OUT STD_LOGIC;
        fmap_a_WEN_B : OUT STD_LOGIC_VECTOR (15 downto 0);
        fmap_a_Din_B : OUT STD_LOGIC_VECTOR (127 downto 0);
        fmap_a_Dout_B : IN STD_LOGIC_VECTOR (127 downto 0);
        fmap_b_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        fmap_b_EN_A : OUT STD_LOGIC;
        fmap_b_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        fmap_b_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
        fmap_b_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
        wt_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        wt_mem_EN_A : OUT STD_LOGIC;
        wt_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        wt_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
        wt_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
        qp_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        qp_mem_EN_A : OUT STD_LOGIC;
        qp_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
        qp_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
        qp_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
        silu_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        silu_mem_EN_A : OUT STD_LOGIC;
        silu_mem_WEN_A : OUT STD_LOGIC_VECTOR (0 downto 0);
        silu_mem_Din_A : OUT STD_LOGIC_VECTOR (7 downto 0);
        silu_mem_Dout_A : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_h_in_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_cin_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_cout_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_wt_base_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_qp_base_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_zp_in_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_zp_out_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_pp_buf_sel_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_pp_rd_offset_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_pp_wr_offset_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_use_silu_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_use_maxpool_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_kh_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component tinyissimo_layer_top_LAYER_CFG_pad_h_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    LAYER_CFG_h_in_U : component tinyissimo_layer_top_LAYER_CFG_h_in_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_h_in_address0,
        ce0 => LAYER_CFG_h_in_ce0_local,
        q0 => LAYER_CFG_h_in_q0);

    LAYER_CFG_w_in_U : component tinyissimo_layer_top_LAYER_CFG_h_in_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_w_in_address0,
        ce0 => LAYER_CFG_w_in_ce0_local,
        q0 => LAYER_CFG_w_in_q0);

    LAYER_CFG_cin_U : component tinyissimo_layer_top_LAYER_CFG_cin_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_cin_address0,
        ce0 => LAYER_CFG_cin_ce0_local,
        q0 => LAYER_CFG_cin_q0);

    LAYER_CFG_cout_U : component tinyissimo_layer_top_LAYER_CFG_cout_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_cout_address0,
        ce0 => LAYER_CFG_cout_ce0_local,
        q0 => LAYER_CFG_cout_q0);

    LAYER_CFG_wt_base_U : component tinyissimo_layer_top_LAYER_CFG_wt_base_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_wt_base_address0,
        ce0 => LAYER_CFG_wt_base_ce0_local,
        q0 => LAYER_CFG_wt_base_q0);

    LAYER_CFG_qp_base_U : component tinyissimo_layer_top_LAYER_CFG_qp_base_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_qp_base_address0,
        ce0 => LAYER_CFG_qp_base_ce0_local,
        q0 => LAYER_CFG_qp_base_q0);

    LAYER_CFG_zp_in_U : component tinyissimo_layer_top_LAYER_CFG_zp_in_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_zp_in_address0,
        ce0 => LAYER_CFG_zp_in_ce0_local,
        q0 => LAYER_CFG_zp_in_q0);

    LAYER_CFG_zp_out_U : component tinyissimo_layer_top_LAYER_CFG_zp_out_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_zp_out_address0,
        ce0 => LAYER_CFG_zp_out_ce0_local,
        q0 => LAYER_CFG_zp_out_q0);

    LAYER_CFG_pp_buf_sel_U : component tinyissimo_layer_top_LAYER_CFG_pp_buf_sel_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_pp_buf_sel_address0,
        ce0 => LAYER_CFG_pp_buf_sel_ce0_local,
        q0 => LAYER_CFG_pp_buf_sel_q0);

    LAYER_CFG_pp_rd_offset_U : component tinyissimo_layer_top_LAYER_CFG_pp_rd_offset_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_pp_rd_offset_address0,
        ce0 => LAYER_CFG_pp_rd_offset_ce0_local,
        q0 => LAYER_CFG_pp_rd_offset_q0);

    LAYER_CFG_pp_wr_offset_U : component tinyissimo_layer_top_LAYER_CFG_pp_wr_offset_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_pp_wr_offset_address0,
        ce0 => LAYER_CFG_pp_wr_offset_ce0_local,
        q0 => LAYER_CFG_pp_wr_offset_q0);

    LAYER_CFG_use_silu_U : component tinyissimo_layer_top_LAYER_CFG_use_silu_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_use_silu_address0,
        ce0 => LAYER_CFG_use_silu_ce0_local,
        q0 => LAYER_CFG_use_silu_q0);

    LAYER_CFG_use_maxpool_U : component tinyissimo_layer_top_LAYER_CFG_use_maxpool_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_use_maxpool_address0,
        ce0 => LAYER_CFG_use_maxpool_ce0_local,
        q0 => LAYER_CFG_use_maxpool_q0);

    LAYER_CFG_kh_U : component tinyissimo_layer_top_LAYER_CFG_kh_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_kh_address0,
        ce0 => LAYER_CFG_kh_ce0_local,
        q0 => LAYER_CFG_kh_q0);

    LAYER_CFG_kw_U : component tinyissimo_layer_top_LAYER_CFG_kh_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_kw_address0,
        ce0 => LAYER_CFG_kw_ce0_local,
        q0 => LAYER_CFG_kw_q0);

    LAYER_CFG_pad_h_U : component tinyissimo_layer_top_LAYER_CFG_pad_h_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_pad_h_address0,
        ce0 => LAYER_CFG_pad_h_ce0_local,
        q0 => LAYER_CFG_pad_h_q0);

    LAYER_CFG_pad_w_U : component tinyissimo_layer_top_LAYER_CFG_pad_h_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 17,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LAYER_CFG_pad_w_address0,
        ce0 => LAYER_CFG_pad_w_ce0_local,
        q0 => LAYER_CFG_pad_w_q0);

    grp_tinyissimo_layer_fu_323 : component tinyissimo_layer_top_tinyissimo_layer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tinyissimo_layer_fu_323_ap_start,
        ap_done => grp_tinyissimo_layer_fu_323_ap_done,
        ap_idle => grp_tinyissimo_layer_fu_323_ap_idle,
        ap_ready => grp_tinyissimo_layer_fu_323_ap_ready,
        in_h => cfg_h_in_reg_532,
        in_w => cfg_w_in_reg_537,
        in_c => cfg_cin_reg_542,
        out_c => cfg_cout_reg_547,
        kh => cfg_kh_reg_596,
        kw => cfg_kw_reg_601,
        pad_h => cfg_pad_h_reg_606,
        pad_w => cfg_pad_w_reg_611,
        use_maxpool => cfg_use_maxpool_reg_591,
        use_silu => cfg_use_silu_reg_586,
        layer_idx => L_fu_90,
        zp_in => cfg_zp_in_reg_562,
        zp_out => cfg_zp_out_reg_567,
        wt_base => cfg_wt_base_reg_552,
        qp_base => cfg_qp_base_reg_557,
        fmap_rd_offset => cfg_pp_rd_offset_reg_576,
        fmap_wr_offset => cfg_pp_wr_offset_reg_581,
        packed_rgb_input => packed_rgb_reg_616,
        fmap_a_Addr_A => grp_tinyissimo_layer_fu_323_fmap_a_Addr_A,
        fmap_a_EN_A => grp_tinyissimo_layer_fu_323_fmap_a_EN_A,
        fmap_a_WEN_A => grp_tinyissimo_layer_fu_323_fmap_a_WEN_A,
        fmap_a_Din_A => grp_tinyissimo_layer_fu_323_fmap_a_Din_A,
        fmap_a_Dout_A => grp_tinyissimo_layer_fu_323_fmap_a_Dout_A,
        fmap_a_Addr_B => grp_tinyissimo_layer_fu_323_fmap_a_Addr_B,
        fmap_a_EN_B => grp_tinyissimo_layer_fu_323_fmap_a_EN_B,
        fmap_a_WEN_B => grp_tinyissimo_layer_fu_323_fmap_a_WEN_B,
        fmap_a_Din_B => grp_tinyissimo_layer_fu_323_fmap_a_Din_B,
        fmap_a_Dout_B => grp_tinyissimo_layer_fu_323_fmap_a_Dout_B,
        fmap_b_Addr_A => grp_tinyissimo_layer_fu_323_fmap_b_Addr_A,
        fmap_b_EN_A => grp_tinyissimo_layer_fu_323_fmap_b_EN_A,
        fmap_b_WEN_A => grp_tinyissimo_layer_fu_323_fmap_b_WEN_A,
        fmap_b_Din_A => grp_tinyissimo_layer_fu_323_fmap_b_Din_A,
        fmap_b_Dout_A => ap_const_lv128_lc_1,
        wt_mem_Addr_A => grp_tinyissimo_layer_fu_323_wt_mem_Addr_A,
        wt_mem_EN_A => grp_tinyissimo_layer_fu_323_wt_mem_EN_A,
        wt_mem_WEN_A => grp_tinyissimo_layer_fu_323_wt_mem_WEN_A,
        wt_mem_Din_A => grp_tinyissimo_layer_fu_323_wt_mem_Din_A,
        wt_mem_Dout_A => wt_mem_Dout_A,
        qp_mem_Addr_A => grp_tinyissimo_layer_fu_323_qp_mem_Addr_A,
        qp_mem_EN_A => grp_tinyissimo_layer_fu_323_qp_mem_EN_A,
        qp_mem_WEN_A => grp_tinyissimo_layer_fu_323_qp_mem_WEN_A,
        qp_mem_Din_A => grp_tinyissimo_layer_fu_323_qp_mem_Din_A,
        qp_mem_Dout_A => qp_mem_Dout_A,
        silu_mem_Addr_A => grp_tinyissimo_layer_fu_323_silu_mem_Addr_A,
        silu_mem_EN_A => grp_tinyissimo_layer_fu_323_silu_mem_EN_A,
        silu_mem_WEN_A => grp_tinyissimo_layer_fu_323_silu_mem_WEN_A,
        silu_mem_Din_A => grp_tinyissimo_layer_fu_323_silu_mem_Din_A,
        silu_mem_Dout_A => silu_mem_Dout_A);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_tinyissimo_layer_fu_323_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tinyissimo_layer_fu_323_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_const_lv1_1 = LAYER_CFG_pp_buf_sel_q0_local) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_lv1_0 = LAYER_CFG_pp_buf_sel_q0_local) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                    grp_tinyissimo_layer_fu_323_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tinyissimo_layer_fu_323_ap_ready = ap_const_logic_1)) then 
                    grp_tinyissimo_layer_fu_323_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    L_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                L_fu_90 <= ap_const_lv5_0;
            elsif (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                L_fu_90 <= add_ln42_reg_442;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln42_reg_442 <= add_ln42_fu_387_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                cfg_cin_reg_542 <= LAYER_CFG_cin_q0;
                cfg_cout_reg_547 <= LAYER_CFG_cout_q0;
                cfg_h_in_reg_532 <= LAYER_CFG_h_in_q0;
                cfg_kh_reg_596 <= LAYER_CFG_kh_q0;
                cfg_kw_reg_601 <= LAYER_CFG_kw_q0;
                cfg_pad_h_reg_606 <= LAYER_CFG_pad_h_q0;
                cfg_pad_w_reg_611 <= LAYER_CFG_pad_w_q0;
                cfg_pp_buf_sel_reg_572 <= LAYER_CFG_pp_buf_sel_q0;
                cfg_pp_rd_offset_reg_576 <= LAYER_CFG_pp_rd_offset_q0;
                cfg_pp_wr_offset_reg_581 <= LAYER_CFG_pp_wr_offset_q0;
                cfg_qp_base_reg_557 <= LAYER_CFG_qp_base_q0;
                cfg_use_maxpool_reg_591 <= LAYER_CFG_use_maxpool_q0;
                cfg_use_silu_reg_586 <= LAYER_CFG_use_silu_q0;
                cfg_w_in_reg_537 <= LAYER_CFG_w_in_q0;
                cfg_wt_base_reg_552 <= LAYER_CFG_wt_base_q0;
                cfg_zp_in_reg_562 <= LAYER_CFG_zp_in_q0;
                cfg_zp_out_reg_567 <= LAYER_CFG_zp_out_q0;
                packed_rgb_reg_616 <= packed_rgb_fu_419_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state4, icmp_ln42_fu_381_p2, ap_block_state4_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln42_fu_381_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    LAYER_CFG_cin_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_cin_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_cin_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_cin_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_cout_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_cout_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_cout_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_cout_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_h_in_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_h_in_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_h_in_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_h_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_kh_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_kh_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_kh_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_kh_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_kw_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_kw_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_kw_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_kw_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_pad_h_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_pad_h_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_pad_h_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_pad_h_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_pad_w_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_pad_w_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_pad_w_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_pad_w_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_pp_buf_sel_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_pp_buf_sel_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_pp_buf_sel_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_pp_buf_sel_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_pp_buf_sel_q0_local <= LAYER_CFG_pp_buf_sel_q0;
    LAYER_CFG_pp_rd_offset_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_pp_rd_offset_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_pp_rd_offset_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_pp_rd_offset_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_pp_wr_offset_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_pp_wr_offset_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_pp_wr_offset_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_pp_wr_offset_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_qp_base_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_qp_base_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_qp_base_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_qp_base_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_use_maxpool_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_use_maxpool_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_use_maxpool_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_use_maxpool_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_use_silu_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_use_silu_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_use_silu_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_use_silu_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_w_in_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_w_in_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_w_in_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_w_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_wt_base_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_wt_base_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_wt_base_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_wt_base_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_zp_in_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_zp_in_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_zp_in_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_zp_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    LAYER_CFG_zp_out_address0 <= zext_ln42_fu_393_p1(5 - 1 downto 0);

    LAYER_CFG_zp_out_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LAYER_CFG_zp_out_ce0_local <= ap_const_logic_1;
        else 
            LAYER_CFG_zp_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln42_fu_387_p2 <= std_logic_vector(unsigned(L_fu_90) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_ap_done)
    begin
                ap_block_state4_on_subcall_done <= (((grp_tinyissimo_layer_fu_323_ap_done = ap_const_logic_0) and (cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) or ((grp_tinyissimo_layer_fu_323_ap_done = ap_const_logic_0) and (cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln42_fu_381_p2)
    begin
        if (((icmp_ln42_fu_381_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln42_fu_381_p2)
    begin
        if (((icmp_ln42_fu_381_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    curr_layer_out_assign_proc : process(ap_CS_fsm_state2, icmp_ln42_fu_381_p2, zext_ln46_fu_414_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((icmp_ln42_fu_381_p2 = ap_const_lv1_1)) then 
                curr_layer_out <= ap_const_lv32_11;
            elsif ((icmp_ln42_fu_381_p2 = ap_const_lv1_0)) then 
                curr_layer_out <= zext_ln46_fu_414_p1;
            else 
                curr_layer_out <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            curr_layer_out <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    curr_layer_out_ap_vld_assign_proc : process(ap_CS_fsm_state2, icmp_ln42_fu_381_p2)
    begin
        if ((((icmp_ln42_fu_381_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln42_fu_381_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            curr_layer_out_ap_vld <= ap_const_logic_1;
        else 
            curr_layer_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fmap_a_Addr_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_Addr_A, grp_tinyissimo_layer_fu_323_fmap_b_Addr_A, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                fmap_a_Addr_A <= grp_tinyissimo_layer_fu_323_fmap_b_Addr_A;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                fmap_a_Addr_A <= grp_tinyissimo_layer_fu_323_fmap_a_Addr_A;
            else 
                fmap_a_Addr_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            fmap_a_Addr_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    fmap_a_Addr_B <= grp_tinyissimo_layer_fu_323_fmap_a_Addr_B;
    fmap_a_Clk_A <= ap_clk;
    fmap_a_Clk_B <= ap_clk;
    fmap_a_Din_A <= grp_tinyissimo_layer_fu_323_fmap_b_Din_A;
    fmap_a_Din_B <= ap_const_lv128_lc_1;

    fmap_a_EN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_EN_A, grp_tinyissimo_layer_fu_323_fmap_b_EN_A, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                fmap_a_EN_A <= grp_tinyissimo_layer_fu_323_fmap_b_EN_A;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                fmap_a_EN_A <= grp_tinyissimo_layer_fu_323_fmap_a_EN_A;
            else 
                fmap_a_EN_A <= ap_const_logic_0;
            end if;
        else 
            fmap_a_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    fmap_a_EN_B_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_EN_B, ap_CS_fsm_state4)
    begin
        if (((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            fmap_a_EN_B <= grp_tinyissimo_layer_fu_323_fmap_a_EN_B;
        else 
            fmap_a_EN_B <= ap_const_logic_0;
        end if; 
    end process;

    fmap_a_Rst_A <= ap_rst;
    fmap_a_Rst_B <= ap_rst;

    fmap_a_WEN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_b_WEN_A, ap_CS_fsm_state4)
    begin
        if (((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            fmap_a_WEN_A <= grp_tinyissimo_layer_fu_323_fmap_b_WEN_A;
        else 
            fmap_a_WEN_A <= ap_const_lv16_0;
        end if; 
    end process;

    fmap_a_WEN_B <= ap_const_lv16_0;

    fmap_b_Addr_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_Addr_A, grp_tinyissimo_layer_fu_323_fmap_b_Addr_A, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                fmap_b_Addr_A <= grp_tinyissimo_layer_fu_323_fmap_b_Addr_A;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                fmap_b_Addr_A <= grp_tinyissimo_layer_fu_323_fmap_a_Addr_A;
            else 
                fmap_b_Addr_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            fmap_b_Addr_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    fmap_b_Addr_B <= grp_tinyissimo_layer_fu_323_fmap_a_Addr_B;
    fmap_b_Clk_A <= ap_clk;
    fmap_b_Clk_B <= ap_clk;
    fmap_b_Din_A <= grp_tinyissimo_layer_fu_323_fmap_b_Din_A;
    fmap_b_Din_B <= ap_const_lv128_lc_1;

    fmap_b_EN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_EN_A, grp_tinyissimo_layer_fu_323_fmap_b_EN_A, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                fmap_b_EN_A <= grp_tinyissimo_layer_fu_323_fmap_b_EN_A;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                fmap_b_EN_A <= grp_tinyissimo_layer_fu_323_fmap_a_EN_A;
            else 
                fmap_b_EN_A <= ap_const_logic_0;
            end if;
        else 
            fmap_b_EN_A <= ap_const_logic_0;
        end if; 
    end process;


    fmap_b_EN_B_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_a_EN_B, ap_CS_fsm_state4)
    begin
        if (((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            fmap_b_EN_B <= grp_tinyissimo_layer_fu_323_fmap_a_EN_B;
        else 
            fmap_b_EN_B <= ap_const_logic_0;
        end if; 
    end process;

    fmap_b_Rst_A <= ap_rst;
    fmap_b_Rst_B <= ap_rst;

    fmap_b_WEN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_fmap_b_WEN_A, ap_CS_fsm_state4)
    begin
        if (((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            fmap_b_WEN_A <= grp_tinyissimo_layer_fu_323_fmap_b_WEN_A;
        else 
            fmap_b_WEN_A <= ap_const_lv16_0;
        end if; 
    end process;

    fmap_b_WEN_B <= ap_const_lv16_0;
    grp_tinyissimo_layer_fu_323_ap_start <= grp_tinyissimo_layer_fu_323_ap_start_reg;

    grp_tinyissimo_layer_fu_323_fmap_a_Dout_A_assign_proc : process(fmap_a_Dout_A, fmap_b_Dout_A, cfg_pp_buf_sel_reg_572, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_A <= fmap_a_Dout_A;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_A <= fmap_b_Dout_A;
            else 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_tinyissimo_layer_fu_323_fmap_a_Dout_A <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_tinyissimo_layer_fu_323_fmap_a_Dout_B_assign_proc : process(fmap_a_Dout_B, fmap_b_Dout_B, cfg_pp_buf_sel_reg_572, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1)) then 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_B <= fmap_a_Dout_B;
            elsif ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0)) then 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_B <= fmap_b_Dout_B;
            else 
                grp_tinyissimo_layer_fu_323_fmap_a_Dout_B <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_tinyissimo_layer_fu_323_fmap_a_Dout_B <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln42_fu_381_p2 <= "1" when (L_fu_90 = ap_const_lv5_11) else "0";
    packed_rgb_fu_419_p2 <= "1" when (L_fu_90 = ap_const_lv5_0) else "0";
    qp_mem_Addr_A <= grp_tinyissimo_layer_fu_323_qp_mem_Addr_A;
    qp_mem_Clk_A <= ap_clk;
    qp_mem_Din_A <= ap_const_lv128_lc_1;

    qp_mem_EN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_qp_mem_EN_A, ap_CS_fsm_state4)
    begin
        if ((((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            qp_mem_EN_A <= grp_tinyissimo_layer_fu_323_qp_mem_EN_A;
        else 
            qp_mem_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    qp_mem_Rst_A <= ap_rst;
    qp_mem_WEN_A <= ap_const_lv16_0;
    silu_mem_Addr_A <= grp_tinyissimo_layer_fu_323_silu_mem_Addr_A;
    silu_mem_Clk_A <= ap_clk;
    silu_mem_Din_A <= ap_const_lv8_0;

    silu_mem_EN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_silu_mem_EN_A, ap_CS_fsm_state4)
    begin
        if ((((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            silu_mem_EN_A <= grp_tinyissimo_layer_fu_323_silu_mem_EN_A;
        else 
            silu_mem_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    silu_mem_Rst_A <= ap_rst;
    silu_mem_WEN_A <= ap_const_lv1_0;
    wt_mem_Addr_A <= grp_tinyissimo_layer_fu_323_wt_mem_Addr_A;
    wt_mem_Clk_A <= ap_clk;
    wt_mem_Din_A <= ap_const_lv128_lc_1;

    wt_mem_EN_A_assign_proc : process(cfg_pp_buf_sel_reg_572, grp_tinyissimo_layer_fu_323_wt_mem_EN_A, ap_CS_fsm_state4)
    begin
        if ((((cfg_pp_buf_sel_reg_572 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((cfg_pp_buf_sel_reg_572 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            wt_mem_EN_A <= grp_tinyissimo_layer_fu_323_wt_mem_EN_A;
        else 
            wt_mem_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    wt_mem_Rst_A <= ap_rst;
    wt_mem_WEN_A <= ap_const_lv16_0;
    zext_ln42_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(L_fu_90),64));
    zext_ln46_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(L_fu_90),32));
end behav;
