-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_WT is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
    kw : IN STD_LOGIC_VECTOR (1 downto 0);
    ic_tiles : IN STD_LOGIC_VECTOR (3 downto 0);
    kh_cast22 : IN STD_LOGIC_VECTOR (1 downto 0);
    wt_base : IN STD_LOGIC_VECTOR (14 downto 0);
    zext_ln181 : IN STD_LOGIC_VECTOR (12 downto 0);
    w_buf_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_ce1 : OUT STD_LOGIC;
    w_buf_we1 : OUT STD_LOGIC;
    w_buf_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_1_ce1 : OUT STD_LOGIC;
    w_buf_1_we1 : OUT STD_LOGIC;
    w_buf_1_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_2_ce1 : OUT STD_LOGIC;
    w_buf_2_we1 : OUT STD_LOGIC;
    w_buf_2_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_3_ce1 : OUT STD_LOGIC;
    w_buf_3_we1 : OUT STD_LOGIC;
    w_buf_3_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_4_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_4_ce1 : OUT STD_LOGIC;
    w_buf_4_we1 : OUT STD_LOGIC;
    w_buf_4_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_5_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_5_ce1 : OUT STD_LOGIC;
    w_buf_5_we1 : OUT STD_LOGIC;
    w_buf_5_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_6_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_6_ce1 : OUT STD_LOGIC;
    w_buf_6_we1 : OUT STD_LOGIC;
    w_buf_6_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_7_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_7_ce1 : OUT STD_LOGIC;
    w_buf_7_we1 : OUT STD_LOGIC;
    w_buf_7_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_8_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_8_ce1 : OUT STD_LOGIC;
    w_buf_8_we1 : OUT STD_LOGIC;
    w_buf_8_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_9_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_9_ce1 : OUT STD_LOGIC;
    w_buf_9_we1 : OUT STD_LOGIC;
    w_buf_9_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_10_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_10_ce1 : OUT STD_LOGIC;
    w_buf_10_we1 : OUT STD_LOGIC;
    w_buf_10_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_11_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_11_ce1 : OUT STD_LOGIC;
    w_buf_11_we1 : OUT STD_LOGIC;
    w_buf_11_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_12_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_12_ce1 : OUT STD_LOGIC;
    w_buf_12_we1 : OUT STD_LOGIC;
    w_buf_12_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_13_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_13_ce1 : OUT STD_LOGIC;
    w_buf_13_we1 : OUT STD_LOGIC;
    w_buf_13_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_14_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_14_ce1 : OUT STD_LOGIC;
    w_buf_14_we1 : OUT STD_LOGIC;
    w_buf_14_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w_buf_15_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w_buf_15_ce1 : OUT STD_LOGIC;
    w_buf_15_we1 : OUT STD_LOGIC;
    w_buf_15_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    wt_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    wt_mem_EN_A : OUT STD_LOGIC;
    wt_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    wt_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    wt_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_WT is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln181_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln181_cast_fu_501_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln181_cast_reg_897 : STD_LOGIC_VECTOR (14 downto 0);
    signal kh_cast22_cast_fu_505_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kh_cast22_cast_reg_902 : STD_LOGIC_VECTOR (31 downto 0);
    signal kw_cast23157_fu_509_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal kw_cast23157_reg_907 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln79_fu_513_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln79_reg_912 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_t_3_reg_917 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln185_3_fu_635_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln185_3_reg_924 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln185_fu_582_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln185_1_fu_833_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal wt_t_fu_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal wt_t_2_fu_744_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal wt_ict_fu_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal wt_ict_3_fu_752_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_kh_fu_152 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal wt_kh_2_fu_780_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_kw_fu_156 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal wt_kw_1_fu_800_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_1_fu_160 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln181_fu_562_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal wt_mem_EN_A_local : STD_LOGIC;
    signal wt_mem_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_mem_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal w_buf_15_we1_local : STD_LOGIC;
    signal w_buf_15_ce1_local : STD_LOGIC;
    signal w_buf_14_we1_local : STD_LOGIC;
    signal w_buf_14_ce1_local : STD_LOGIC;
    signal w_buf_13_we1_local : STD_LOGIC;
    signal w_buf_13_ce1_local : STD_LOGIC;
    signal w_buf_12_we1_local : STD_LOGIC;
    signal w_buf_12_ce1_local : STD_LOGIC;
    signal w_buf_11_we1_local : STD_LOGIC;
    signal w_buf_11_ce1_local : STD_LOGIC;
    signal w_buf_10_we1_local : STD_LOGIC;
    signal w_buf_10_ce1_local : STD_LOGIC;
    signal w_buf_9_we1_local : STD_LOGIC;
    signal w_buf_9_ce1_local : STD_LOGIC;
    signal w_buf_8_we1_local : STD_LOGIC;
    signal w_buf_8_ce1_local : STD_LOGIC;
    signal w_buf_7_we1_local : STD_LOGIC;
    signal w_buf_7_ce1_local : STD_LOGIC;
    signal w_buf_6_we1_local : STD_LOGIC;
    signal w_buf_6_ce1_local : STD_LOGIC;
    signal w_buf_5_we1_local : STD_LOGIC;
    signal w_buf_5_ce1_local : STD_LOGIC;
    signal w_buf_4_we1_local : STD_LOGIC;
    signal w_buf_4_ce1_local : STD_LOGIC;
    signal w_buf_3_we1_local : STD_LOGIC;
    signal w_buf_3_ce1_local : STD_LOGIC;
    signal w_buf_2_we1_local : STD_LOGIC;
    signal w_buf_2_ce1_local : STD_LOGIC;
    signal w_buf_1_we1_local : STD_LOGIC;
    signal w_buf_1_ce1_local : STD_LOGIC;
    signal w_buf_we1_local : STD_LOGIC;
    signal w_buf_ce1_local : STD_LOGIC;
    signal zext_ln181_1_fu_568_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln185_1_fu_572_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln185_fu_577_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln185_1_fu_591_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_595_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln185_fu_587_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln185_fu_603_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln185_2_fu_609_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln185_2_fu_613_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln185_fu_619_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln185_1_fu_625_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln185_3_fu_631_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal wt_kw_4_fu_677_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_kh_4_fu_688_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_ict_5_fu_699_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln192_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln192_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln194_fu_716_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln188_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln190_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln190_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal wt_t_4_fu_722_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_ict_6_fu_730_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln188_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln190_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal wt_kh_2_fu_780_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal wt_kh_2_fu_780_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal wt_kh_2_fu_780_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal wt_kh_2_fu_780_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal wt_kh_2_fu_780_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component tinyissimo_layer_top_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_7_2_32_1_1_U357 : component tinyissimo_layer_top_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "00",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => wt_kh_fu_152,
        din1 => wt_kh_4_fu_688_p2,
        din2 => ap_const_lv32_0,
        def => wt_kh_2_fu_780_p7,
        sel => wt_kh_2_fu_780_p8,
        dout => wt_kh_2_fu_780_p9);

    flow_control_loop_pipe_sequential_init_U : component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_160 <= ap_const_lv11_0;
                elsif (((icmp_ln181_fu_557_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_1_fu_160 <= add_ln181_fu_562_p2;
                end if;
            end if; 
        end if;
    end process;

    wt_ict_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    wt_ict_fu_148 <= ap_const_lv32_0;
                elsif (((icmp_ln181_fu_557_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    wt_ict_fu_148 <= wt_ict_3_fu_752_p3;
                end if;
            end if; 
        end if;
    end process;

    wt_kh_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    wt_kh_fu_152 <= ap_const_lv32_0;
                elsif (((icmp_ln181_fu_557_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    wt_kh_fu_152 <= wt_kh_2_fu_780_p9;
                end if;
            end if; 
        end if;
    end process;

    wt_kw_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    wt_kw_fu_156 <= ap_const_lv32_0;
                elsif (((icmp_ln181_fu_557_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    wt_kw_fu_156 <= wt_kw_1_fu_800_p3;
                end if;
            end if; 
        end if;
    end process;

    wt_t_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    wt_t_fu_144 <= ap_const_lv32_0;
                elsif (((icmp_ln181_fu_557_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    wt_t_fu_144 <= wt_t_2_fu_744_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln185_3_reg_924 <= add_ln185_3_fu_635_p2;
                    kh_cast22_cast_reg_902(1 downto 0) <= kh_cast22_cast_fu_505_p1(1 downto 0);
                    kw_cast23157_reg_907(1 downto 0) <= kw_cast23157_fu_509_p1(1 downto 0);
                wt_t_3_reg_917 <= wt_t_fu_144;
                    zext_ln181_cast_reg_897(12 downto 0) <= zext_ln181_cast_fu_501_p1(12 downto 0);
                    zext_ln79_reg_912(3 downto 0) <= zext_ln79_fu_513_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln181_cast_reg_897(14 downto 13) <= "00";
    kh_cast22_cast_reg_902(31 downto 2) <= "000000000000000000000000000000";
    kw_cast23157_reg_907(31 downto 2) <= "000000000000000000000000000000";
    zext_ln79_reg_912(31 downto 4) <= "0000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln181_fu_562_p2 <= std_logic_vector(unsigned(i_1_fu_160) + unsigned(ap_const_lv11_1));
    add_ln185_1_fu_572_p2 <= std_logic_vector(unsigned(zext_ln181_1_fu_568_p1) + unsigned(wt_base));
    add_ln185_2_fu_613_p2 <= std_logic_vector(unsigned(sub_ln185_fu_603_p2) + unsigned(trunc_ln185_2_fu_609_p1));
    add_ln185_3_fu_635_p2 <= std_logic_vector(unsigned(sub_ln185_1_fu_625_p2) + unsigned(trunc_ln185_3_fu_631_p1));
    add_ln185_fu_577_p2 <= std_logic_vector(unsigned(add_ln185_1_fu_572_p2) + unsigned(zext_ln181_cast_reg_897));
    add_ln194_fu_716_p2 <= std_logic_vector(unsigned(wt_t_fu_144) + unsigned(ap_const_lv32_1));
    and_ln190_fu_766_p2 <= (xor_ln188_fu_760_p2 and icmp_ln190_fu_694_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln181_fu_557_p2)
    begin
        if (((icmp_ln181_fu_557_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln181_fu_557_p2 <= "1" when (i_1_fu_160 = shl_ln) else "0";
    icmp_ln188_fu_683_p2 <= "1" when (signed(wt_kw_4_fu_677_p2) < signed(kw_cast23157_reg_907)) else "0";
    icmp_ln190_fu_694_p2 <= "1" when (signed(wt_kh_4_fu_688_p2) < signed(kh_cast22_cast_reg_902)) else "0";
    icmp_ln192_fu_705_p2 <= "1" when (signed(wt_ict_5_fu_699_p2) < signed(zext_ln79_reg_912)) else "0";
    kh_cast22_cast_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kh_cast22),32));
    kw_cast23157_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kw),32));
    or_ln190_fu_738_p2 <= (icmp_ln190_fu_694_p2 or icmp_ln188_fu_683_p2);
    p_shl_fu_595_p3 <= (trunc_ln185_1_fu_591_p1 & ap_const_lv2_0);
    shl_ln185_fu_619_p2 <= std_logic_vector(shift_left(unsigned(add_ln185_2_fu_613_p2),to_integer(unsigned('0' & ap_const_lv7_2(7-1 downto 0)))));
    sub_ln185_1_fu_625_p2 <= std_logic_vector(unsigned(shl_ln185_fu_619_p2) - unsigned(add_ln185_2_fu_613_p2));
    sub_ln185_fu_603_p2 <= std_logic_vector(unsigned(p_shl_fu_595_p3) - unsigned(trunc_ln185_fu_587_p1));
    trunc_ln185_1_fu_591_p1 <= wt_ict_fu_148(5 - 1 downto 0);
    trunc_ln185_2_fu_609_p1 <= wt_kh_fu_152(7 - 1 downto 0);
    trunc_ln185_3_fu_631_p1 <= wt_kw_fu_156(7 - 1 downto 0);
    trunc_ln185_fu_587_p1 <= wt_ict_fu_148(7 - 1 downto 0);
    w_buf_10_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_10_ce1 <= w_buf_10_ce1_local;

    w_buf_10_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_10_ce1_local <= ap_const_logic_1;
        else 
            w_buf_10_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_10_d1 <= wt_mem_Dout_A;
    w_buf_10_we1 <= w_buf_10_we1_local;

    w_buf_10_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_A))) then 
            w_buf_10_we1_local <= ap_const_logic_1;
        else 
            w_buf_10_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_11_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_11_ce1 <= w_buf_11_ce1_local;

    w_buf_11_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_11_ce1_local <= ap_const_logic_1;
        else 
            w_buf_11_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_11_d1 <= wt_mem_Dout_A;
    w_buf_11_we1 <= w_buf_11_we1_local;

    w_buf_11_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_B))) then 
            w_buf_11_we1_local <= ap_const_logic_1;
        else 
            w_buf_11_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_12_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_12_ce1 <= w_buf_12_ce1_local;

    w_buf_12_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_12_ce1_local <= ap_const_logic_1;
        else 
            w_buf_12_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_12_d1 <= wt_mem_Dout_A;
    w_buf_12_we1 <= w_buf_12_we1_local;

    w_buf_12_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_C))) then 
            w_buf_12_we1_local <= ap_const_logic_1;
        else 
            w_buf_12_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_13_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_13_ce1 <= w_buf_13_ce1_local;

    w_buf_13_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_13_ce1_local <= ap_const_logic_1;
        else 
            w_buf_13_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_13_d1 <= wt_mem_Dout_A;
    w_buf_13_we1 <= w_buf_13_we1_local;

    w_buf_13_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_D))) then 
            w_buf_13_we1_local <= ap_const_logic_1;
        else 
            w_buf_13_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_14_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_14_ce1 <= w_buf_14_ce1_local;

    w_buf_14_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_14_ce1_local <= ap_const_logic_1;
        else 
            w_buf_14_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_14_d1 <= wt_mem_Dout_A;
    w_buf_14_we1 <= w_buf_14_we1_local;

    w_buf_14_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_E))) then 
            w_buf_14_we1_local <= ap_const_logic_1;
        else 
            w_buf_14_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_15_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_15_ce1 <= w_buf_15_ce1_local;

    w_buf_15_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_15_ce1_local <= ap_const_logic_1;
        else 
            w_buf_15_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_15_d1 <= wt_mem_Dout_A;
    w_buf_15_we1 <= w_buf_15_we1_local;

    w_buf_15_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_F))) then 
            w_buf_15_we1_local <= ap_const_logic_1;
        else 
            w_buf_15_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_1_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_1_ce1 <= w_buf_1_ce1_local;

    w_buf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_1_ce1_local <= ap_const_logic_1;
        else 
            w_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_1_d1 <= wt_mem_Dout_A;
    w_buf_1_we1 <= w_buf_1_we1_local;

    w_buf_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_1))) then 
            w_buf_1_we1_local <= ap_const_logic_1;
        else 
            w_buf_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_2_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_2_ce1 <= w_buf_2_ce1_local;

    w_buf_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_2_ce1_local <= ap_const_logic_1;
        else 
            w_buf_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_2_d1 <= wt_mem_Dout_A;
    w_buf_2_we1 <= w_buf_2_we1_local;

    w_buf_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_2))) then 
            w_buf_2_we1_local <= ap_const_logic_1;
        else 
            w_buf_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_3_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_3_ce1 <= w_buf_3_ce1_local;

    w_buf_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_3_ce1_local <= ap_const_logic_1;
        else 
            w_buf_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_3_d1 <= wt_mem_Dout_A;
    w_buf_3_we1 <= w_buf_3_we1_local;

    w_buf_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_3))) then 
            w_buf_3_we1_local <= ap_const_logic_1;
        else 
            w_buf_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_4_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_4_ce1 <= w_buf_4_ce1_local;

    w_buf_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_4_ce1_local <= ap_const_logic_1;
        else 
            w_buf_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_4_d1 <= wt_mem_Dout_A;
    w_buf_4_we1 <= w_buf_4_we1_local;

    w_buf_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_4))) then 
            w_buf_4_we1_local <= ap_const_logic_1;
        else 
            w_buf_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_5_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_5_ce1 <= w_buf_5_ce1_local;

    w_buf_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_5_ce1_local <= ap_const_logic_1;
        else 
            w_buf_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_5_d1 <= wt_mem_Dout_A;
    w_buf_5_we1 <= w_buf_5_we1_local;

    w_buf_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_5))) then 
            w_buf_5_we1_local <= ap_const_logic_1;
        else 
            w_buf_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_6_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_6_ce1 <= w_buf_6_ce1_local;

    w_buf_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_6_ce1_local <= ap_const_logic_1;
        else 
            w_buf_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_6_d1 <= wt_mem_Dout_A;
    w_buf_6_we1 <= w_buf_6_we1_local;

    w_buf_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_6))) then 
            w_buf_6_we1_local <= ap_const_logic_1;
        else 
            w_buf_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_7_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_7_ce1 <= w_buf_7_ce1_local;

    w_buf_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_7_ce1_local <= ap_const_logic_1;
        else 
            w_buf_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_7_d1 <= wt_mem_Dout_A;
    w_buf_7_we1 <= w_buf_7_we1_local;

    w_buf_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_7))) then 
            w_buf_7_we1_local <= ap_const_logic_1;
        else 
            w_buf_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_8_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_8_ce1 <= w_buf_8_ce1_local;

    w_buf_8_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_8_ce1_local <= ap_const_logic_1;
        else 
            w_buf_8_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_8_d1 <= wt_mem_Dout_A;
    w_buf_8_we1 <= w_buf_8_we1_local;

    w_buf_8_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_8))) then 
            w_buf_8_we1_local <= ap_const_logic_1;
        else 
            w_buf_8_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_9_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_9_ce1 <= w_buf_9_ce1_local;

    w_buf_9_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_9_ce1_local <= ap_const_logic_1;
        else 
            w_buf_9_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_9_d1 <= wt_mem_Dout_A;
    w_buf_9_we1 <= w_buf_9_we1_local;

    w_buf_9_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_9))) then 
            w_buf_9_we1_local <= ap_const_logic_1;
        else 
            w_buf_9_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_address1 <= zext_ln185_1_fu_833_p1(7 - 1 downto 0);
    w_buf_ce1 <= w_buf_ce1_local;

    w_buf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_ce1_local <= ap_const_logic_1;
        else 
            w_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_d1 <= wt_mem_Dout_A;
    w_buf_we1 <= w_buf_we1_local;

    w_buf_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, wt_t_3_reg_917)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (wt_t_3_reg_917 = ap_const_lv32_0))) then 
            w_buf_we1_local <= ap_const_logic_1;
        else 
            w_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    wt_ict_3_fu_752_p3 <= 
        wt_ict_fu_148 when (or_ln190_fu_738_p2(0) = '1') else 
        wt_ict_6_fu_730_p3;
    wt_ict_5_fu_699_p2 <= std_logic_vector(unsigned(wt_ict_fu_148) + unsigned(ap_const_lv32_1));
    wt_ict_6_fu_730_p3 <= 
        ap_const_lv32_0 when (xor_ln192_fu_710_p2(0) = '1') else 
        wt_ict_5_fu_699_p2;
    wt_kh_2_fu_780_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    wt_kh_2_fu_780_p8 <= (icmp_ln188_fu_683_p2 & and_ln190_fu_766_p2);
    wt_kh_4_fu_688_p2 <= std_logic_vector(unsigned(wt_kh_fu_152) + unsigned(ap_const_lv32_1));
    wt_kw_1_fu_800_p3 <= 
        wt_kw_4_fu_677_p2 when (icmp_ln188_fu_683_p2(0) = '1') else 
        ap_const_lv32_0;
    wt_kw_4_fu_677_p2 <= std_logic_vector(unsigned(wt_kw_fu_156) + unsigned(ap_const_lv32_1));
    wt_mem_Addr_A <= wt_mem_Addr_A_local;
    wt_mem_Addr_A_local <= std_logic_vector(shift_left(unsigned(wt_mem_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    wt_mem_Addr_A_orig <= zext_ln185_fu_582_p1(32 - 1 downto 0);
    wt_mem_Din_A <= ap_const_lv128_lc_1;
    wt_mem_EN_A <= wt_mem_EN_A_local;

    wt_mem_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            wt_mem_EN_A_local <= ap_const_logic_1;
        else 
            wt_mem_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    wt_mem_WEN_A <= ap_const_lv16_0;
    wt_t_2_fu_744_p3 <= 
        wt_t_fu_144 when (or_ln190_fu_738_p2(0) = '1') else 
        wt_t_4_fu_722_p3;
    wt_t_4_fu_722_p3 <= 
        add_ln194_fu_716_p2 when (xor_ln192_fu_710_p2(0) = '1') else 
        wt_t_fu_144;
    xor_ln188_fu_760_p2 <= (icmp_ln188_fu_683_p2 xor ap_const_lv1_1);
    xor_ln192_fu_710_p2 <= (icmp_ln192_fu_705_p2 xor ap_const_lv1_1);
    zext_ln181_1_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_160),15));
    zext_ln181_cast_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln181),15));
    zext_ln185_1_fu_833_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln185_3_reg_924),64));
    zext_ln185_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln185_fu_577_p2),64));
    zext_ln79_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_tiles),32));
end behav;
