-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_QP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    nshift_buf_15 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_14 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_12 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_11 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf : IN STD_LOGIC_VECTOR (7 downto 0);
    m0_buf_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf : IN STD_LOGIC_VECTOR (31 downto 0);
    qp_base : IN STD_LOGIC_VECTOR (9 downto 0);
    zext_ln151 : IN STD_LOGIC_VECTOR (6 downto 0);
    qp_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    qp_mem_EN_A : OUT STD_LOGIC;
    qp_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    qp_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    qp_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    oc_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    nshift_buf_31_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_31_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_30_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_30_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_29_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_29_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_28_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_28_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_27_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_27_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_26_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_26_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_25_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_25_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_24_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_24_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_23_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_23_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_22_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_22_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_21_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_21_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_20_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_20_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_19_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_19_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_18_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_18_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_17_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_17_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_16_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_16_out_ap_vld : OUT STD_LOGIC;
    m0_buf_31_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_31_out_ap_vld : OUT STD_LOGIC;
    m0_buf_30_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_30_out_ap_vld : OUT STD_LOGIC;
    m0_buf_29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_29_out_ap_vld : OUT STD_LOGIC;
    m0_buf_28_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_28_out_ap_vld : OUT STD_LOGIC;
    m0_buf_27_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_27_out_ap_vld : OUT STD_LOGIC;
    m0_buf_26_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_26_out_ap_vld : OUT STD_LOGIC;
    m0_buf_25_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_25_out_ap_vld : OUT STD_LOGIC;
    m0_buf_24_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_24_out_ap_vld : OUT STD_LOGIC;
    m0_buf_23_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_23_out_ap_vld : OUT STD_LOGIC;
    m0_buf_22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_22_out_ap_vld : OUT STD_LOGIC;
    m0_buf_21_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_21_out_ap_vld : OUT STD_LOGIC;
    m0_buf_20_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_20_out_ap_vld : OUT STD_LOGIC;
    m0_buf_19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_19_out_ap_vld : OUT STD_LOGIC;
    m0_buf_18_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_18_out_ap_vld : OUT STD_LOGIC;
    m0_buf_17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_17_out_ap_vld : OUT STD_LOGIC;
    m0_buf_16_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_16_out_ap_vld : OUT STD_LOGIC;
    bias_buf_31_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_31_out_ap_vld : OUT STD_LOGIC;
    bias_buf_30_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_30_out_ap_vld : OUT STD_LOGIC;
    bias_buf_29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_29_out_ap_vld : OUT STD_LOGIC;
    bias_buf_28_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_28_out_ap_vld : OUT STD_LOGIC;
    bias_buf_27_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_27_out_ap_vld : OUT STD_LOGIC;
    bias_buf_26_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_26_out_ap_vld : OUT STD_LOGIC;
    bias_buf_25_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_25_out_ap_vld : OUT STD_LOGIC;
    bias_buf_24_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_24_out_ap_vld : OUT STD_LOGIC;
    bias_buf_23_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_23_out_ap_vld : OUT STD_LOGIC;
    bias_buf_22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_22_out_ap_vld : OUT STD_LOGIC;
    bias_buf_21_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_21_out_ap_vld : OUT STD_LOGIC;
    bias_buf_20_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_20_out_ap_vld : OUT STD_LOGIC;
    bias_buf_19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_19_out_ap_vld : OUT STD_LOGIC;
    bias_buf_18_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_18_out_ap_vld : OUT STD_LOGIC;
    bias_buf_17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_17_out_ap_vld : OUT STD_LOGIC;
    bias_buf_16_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_16_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_QP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln151_fu_1387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln151_fu_1403_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln151_reg_2573 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln153_fu_1407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_reg_2577 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln156_fu_1457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal t_fu_284 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln151_fu_1393_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_t_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal bias_buf_16_fu_288 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_32_fu_1726_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m0_buf_16_fu_292 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal nshift_buf_16_fu_296 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zext_ln159_fu_1746_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bias_buf_17_fu_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_18_fu_304 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_19_fu_308 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_20_fu_312 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_21_fu_316 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_22_fu_320 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_23_fu_324 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_24_fu_328 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_25_fu_332 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_26_fu_336 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_27_fu_340 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_28_fu_344 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_29_fu_348 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_30_fu_352 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_31_fu_356 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_17_fu_360 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_18_fu_364 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_19_fu_368 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_20_fu_372 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_21_fu_376 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_22_fu_380 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_23_fu_384 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_24_fu_388 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_25_fu_392 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_26_fu_396 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_27_fu_400 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_28_fu_404 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_29_fu_408 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_30_fu_412 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_31_fu_416 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal nshift_buf_17_fu_420 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_18_fu_424 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_19_fu_428 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_20_fu_432 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_21_fu_436 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_22_fu_440 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_23_fu_444 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_24_fu_448 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_25_fu_452 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_26_fu_456 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_27_fu_460 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_28_fu_464 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_29_fu_468 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_30_fu_472 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_31_fu_476 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal qp_mem_EN_A_local : STD_LOGIC;
    signal qp_mem_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal qp_mem_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln151_1_fu_1399_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln156_fu_1445_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln151_cast_fu_1135_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln156_1_fu_1451_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal nshift_buf_32_fu_1738_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_663 : BOOLEAN;
    signal ap_condition_667 : BOOLEAN;
    signal ap_condition_670 : BOOLEAN;
    signal ap_condition_673 : BOOLEAN;
    signal ap_condition_676 : BOOLEAN;
    signal ap_condition_679 : BOOLEAN;
    signal ap_condition_682 : BOOLEAN;
    signal ap_condition_685 : BOOLEAN;
    signal ap_condition_688 : BOOLEAN;
    signal ap_condition_691 : BOOLEAN;
    signal ap_condition_694 : BOOLEAN;
    signal ap_condition_697 : BOOLEAN;
    signal ap_condition_700 : BOOLEAN;
    signal ap_condition_703 : BOOLEAN;
    signal ap_condition_706 : BOOLEAN;
    signal ap_condition_709 : BOOLEAN;
    signal ap_condition_712 : BOOLEAN;
    signal ap_condition_715 : BOOLEAN;
    signal ap_condition_718 : BOOLEAN;
    signal ap_condition_721 : BOOLEAN;
    signal ap_condition_724 : BOOLEAN;
    signal ap_condition_727 : BOOLEAN;
    signal ap_condition_730 : BOOLEAN;
    signal ap_condition_733 : BOOLEAN;
    signal ap_condition_736 : BOOLEAN;
    signal ap_condition_739 : BOOLEAN;
    signal ap_condition_742 : BOOLEAN;
    signal ap_condition_745 : BOOLEAN;
    signal ap_condition_748 : BOOLEAN;
    signal ap_condition_751 : BOOLEAN;
    signal ap_condition_754 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    bias_buf_16_fu_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_16_fu_288 <= bias_buf;
                elsif ((ap_const_boolean_1 = ap_condition_663)) then 
                    bias_buf_16_fu_288 <= bias_buf_32_fu_1726_p1;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_17_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_17_fu_300 <= bias_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_670)) then 
                    bias_buf_17_fu_300 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_667)) then 
                    bias_buf_17_fu_300 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_18_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_18_fu_304 <= bias_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_676)) then 
                    bias_buf_18_fu_304 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_673)) then 
                    bias_buf_18_fu_304 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_19_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_19_fu_308 <= bias_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_682)) then 
                    bias_buf_19_fu_308 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_679)) then 
                    bias_buf_19_fu_308 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_20_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_20_fu_312 <= bias_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_688)) then 
                    bias_buf_20_fu_312 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_685)) then 
                    bias_buf_20_fu_312 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_21_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_21_fu_316 <= bias_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_694)) then 
                    bias_buf_21_fu_316 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_691)) then 
                    bias_buf_21_fu_316 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_22_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_22_fu_320 <= bias_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_700)) then 
                    bias_buf_22_fu_320 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_697)) then 
                    bias_buf_22_fu_320 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_23_fu_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_23_fu_324 <= bias_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_706)) then 
                    bias_buf_23_fu_324 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_703)) then 
                    bias_buf_23_fu_324 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_24_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_24_fu_328 <= bias_buf_8;
                elsif ((ap_const_boolean_1 = ap_condition_712)) then 
                    bias_buf_24_fu_328 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_709)) then 
                    bias_buf_24_fu_328 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_25_fu_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_25_fu_332 <= bias_buf_9;
                elsif ((ap_const_boolean_1 = ap_condition_718)) then 
                    bias_buf_25_fu_332 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_715)) then 
                    bias_buf_25_fu_332 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_26_fu_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_26_fu_336 <= bias_buf_10;
                elsif ((ap_const_boolean_1 = ap_condition_724)) then 
                    bias_buf_26_fu_336 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_721)) then 
                    bias_buf_26_fu_336 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_27_fu_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_27_fu_340 <= bias_buf_11;
                elsif ((ap_const_boolean_1 = ap_condition_730)) then 
                    bias_buf_27_fu_340 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_727)) then 
                    bias_buf_27_fu_340 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_28_fu_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_28_fu_344 <= bias_buf_12;
                elsif ((ap_const_boolean_1 = ap_condition_736)) then 
                    bias_buf_28_fu_344 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_733)) then 
                    bias_buf_28_fu_344 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_29_fu_348_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_29_fu_348 <= bias_buf_13;
                elsif ((ap_const_boolean_1 = ap_condition_742)) then 
                    bias_buf_29_fu_348 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_739)) then 
                    bias_buf_29_fu_348 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_30_fu_352_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_30_fu_352 <= bias_buf_14;
                elsif ((ap_const_boolean_1 = ap_condition_748)) then 
                    bias_buf_30_fu_352 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_745)) then 
                    bias_buf_30_fu_352 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_31_fu_356_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_31_fu_356 <= bias_buf_15;
                elsif ((ap_const_boolean_1 = ap_condition_754)) then 
                    bias_buf_31_fu_356 <= bias_buf_32_fu_1726_p1;
                elsif ((ap_const_boolean_1 = ap_condition_751)) then 
                    bias_buf_31_fu_356 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_16_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_16_fu_292 <= m0_buf;
                elsif ((ap_const_boolean_1 = ap_condition_663)) then 
                    m0_buf_16_fu_292 <= qp_mem_Dout_A(63 downto 32);
                end if;
            end if; 
        end if;
    end process;

    m0_buf_17_fu_360_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_17_fu_360 <= m0_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_670)) then 
                    m0_buf_17_fu_360 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_667)) then 
                    m0_buf_17_fu_360 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_18_fu_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_18_fu_364 <= m0_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_676)) then 
                    m0_buf_18_fu_364 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_673)) then 
                    m0_buf_18_fu_364 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_19_fu_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_19_fu_368 <= m0_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_682)) then 
                    m0_buf_19_fu_368 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_679)) then 
                    m0_buf_19_fu_368 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_20_fu_372_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_20_fu_372 <= m0_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_688)) then 
                    m0_buf_20_fu_372 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_685)) then 
                    m0_buf_20_fu_372 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_21_fu_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_21_fu_376 <= m0_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_694)) then 
                    m0_buf_21_fu_376 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_691)) then 
                    m0_buf_21_fu_376 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_22_fu_380_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_22_fu_380 <= m0_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_700)) then 
                    m0_buf_22_fu_380 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_697)) then 
                    m0_buf_22_fu_380 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_23_fu_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_23_fu_384 <= m0_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_706)) then 
                    m0_buf_23_fu_384 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_703)) then 
                    m0_buf_23_fu_384 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_24_fu_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_24_fu_388 <= m0_buf_8;
                elsif ((ap_const_boolean_1 = ap_condition_712)) then 
                    m0_buf_24_fu_388 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_709)) then 
                    m0_buf_24_fu_388 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_25_fu_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_25_fu_392 <= m0_buf_9;
                elsif ((ap_const_boolean_1 = ap_condition_718)) then 
                    m0_buf_25_fu_392 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_715)) then 
                    m0_buf_25_fu_392 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_26_fu_396_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_26_fu_396 <= m0_buf_10;
                elsif ((ap_const_boolean_1 = ap_condition_724)) then 
                    m0_buf_26_fu_396 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_721)) then 
                    m0_buf_26_fu_396 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_27_fu_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_27_fu_400 <= m0_buf_11;
                elsif ((ap_const_boolean_1 = ap_condition_730)) then 
                    m0_buf_27_fu_400 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_727)) then 
                    m0_buf_27_fu_400 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_28_fu_404_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_28_fu_404 <= m0_buf_12;
                elsif ((ap_const_boolean_1 = ap_condition_736)) then 
                    m0_buf_28_fu_404 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_733)) then 
                    m0_buf_28_fu_404 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_29_fu_408_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_29_fu_408 <= m0_buf_13;
                elsif ((ap_const_boolean_1 = ap_condition_742)) then 
                    m0_buf_29_fu_408 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_739)) then 
                    m0_buf_29_fu_408 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_30_fu_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_30_fu_412 <= m0_buf_14;
                elsif ((ap_const_boolean_1 = ap_condition_748)) then 
                    m0_buf_30_fu_412 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_745)) then 
                    m0_buf_30_fu_412 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_31_fu_416_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_31_fu_416 <= m0_buf_15;
                elsif ((ap_const_boolean_1 = ap_condition_754)) then 
                    m0_buf_31_fu_416 <= qp_mem_Dout_A(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_751)) then 
                    m0_buf_31_fu_416 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_16_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_16_fu_296 <= nshift_buf;
                elsif ((ap_const_boolean_1 = ap_condition_663)) then 
                    nshift_buf_16_fu_296 <= zext_ln159_fu_1746_p1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_17_fu_420_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_17_fu_420 <= nshift_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_670)) then 
                    nshift_buf_17_fu_420 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_667)) then 
                    nshift_buf_17_fu_420 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_18_fu_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_18_fu_424 <= nshift_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_676)) then 
                    nshift_buf_18_fu_424 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_673)) then 
                    nshift_buf_18_fu_424 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_19_fu_428_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_19_fu_428 <= nshift_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_682)) then 
                    nshift_buf_19_fu_428 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_679)) then 
                    nshift_buf_19_fu_428 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_20_fu_432_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_20_fu_432 <= nshift_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_688)) then 
                    nshift_buf_20_fu_432 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_685)) then 
                    nshift_buf_20_fu_432 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_21_fu_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_21_fu_436 <= nshift_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_694)) then 
                    nshift_buf_21_fu_436 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_691)) then 
                    nshift_buf_21_fu_436 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_22_fu_440_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_22_fu_440 <= nshift_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_700)) then 
                    nshift_buf_22_fu_440 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_697)) then 
                    nshift_buf_22_fu_440 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_23_fu_444_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_23_fu_444 <= nshift_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_706)) then 
                    nshift_buf_23_fu_444 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_703)) then 
                    nshift_buf_23_fu_444 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_24_fu_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_24_fu_448 <= nshift_buf_8;
                elsif ((ap_const_boolean_1 = ap_condition_712)) then 
                    nshift_buf_24_fu_448 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_709)) then 
                    nshift_buf_24_fu_448 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_25_fu_452_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_25_fu_452 <= nshift_buf_9;
                elsif ((ap_const_boolean_1 = ap_condition_718)) then 
                    nshift_buf_25_fu_452 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_715)) then 
                    nshift_buf_25_fu_452 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_26_fu_456_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_26_fu_456 <= nshift_buf_10;
                elsif ((ap_const_boolean_1 = ap_condition_724)) then 
                    nshift_buf_26_fu_456 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_721)) then 
                    nshift_buf_26_fu_456 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_27_fu_460_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_27_fu_460 <= nshift_buf_11;
                elsif ((ap_const_boolean_1 = ap_condition_730)) then 
                    nshift_buf_27_fu_460 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_727)) then 
                    nshift_buf_27_fu_460 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_28_fu_464_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_28_fu_464 <= nshift_buf_12;
                elsif ((ap_const_boolean_1 = ap_condition_736)) then 
                    nshift_buf_28_fu_464 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_733)) then 
                    nshift_buf_28_fu_464 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_29_fu_468_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_29_fu_468 <= nshift_buf_13;
                elsif ((ap_const_boolean_1 = ap_condition_742)) then 
                    nshift_buf_29_fu_468 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_739)) then 
                    nshift_buf_29_fu_468 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_30_fu_472_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_30_fu_472 <= nshift_buf_14;
                elsif ((ap_const_boolean_1 = ap_condition_748)) then 
                    nshift_buf_30_fu_472 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_745)) then 
                    nshift_buf_30_fu_472 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_31_fu_476_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_31_fu_476 <= nshift_buf_15;
                elsif ((ap_const_boolean_1 = ap_condition_754)) then 
                    nshift_buf_31_fu_476 <= zext_ln159_fu_1746_p1;
                elsif ((ap_const_boolean_1 = ap_condition_751)) then 
                    nshift_buf_31_fu_476 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    t_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_1387_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_284 <= add_ln151_fu_1393_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_284 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln153_reg_2577 <= icmp_ln153_fu_1407_p2;
                trunc_ln151_reg_2573 <= trunc_ln151_fu_1403_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln151_fu_1393_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_1) + unsigned(ap_const_lv5_1));
    add_ln156_1_fu_1451_p2 <= std_logic_vector(unsigned(add_ln156_fu_1445_p2) + unsigned(zext_ln151_cast_fu_1135_p1));
    add_ln156_fu_1445_p2 <= std_logic_vector(unsigned(zext_ln151_1_fu_1399_p1) + unsigned(qp_base));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_663_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_663 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_0));
    end process;


    ap_condition_667_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_667 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_1));
    end process;


    ap_condition_670_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_670 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_1));
    end process;


    ap_condition_673_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_673 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_2));
    end process;


    ap_condition_676_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_676 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_2));
    end process;


    ap_condition_679_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_679 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_3));
    end process;


    ap_condition_682_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_682 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_3));
    end process;


    ap_condition_685_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_685 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_4));
    end process;


    ap_condition_688_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_688 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_4));
    end process;


    ap_condition_691_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_691 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_5));
    end process;


    ap_condition_694_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_694 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_5));
    end process;


    ap_condition_697_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_697 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_6));
    end process;


    ap_condition_700_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_700 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_6));
    end process;


    ap_condition_703_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_703 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_7));
    end process;


    ap_condition_706_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_706 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_7));
    end process;


    ap_condition_709_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_709 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_8));
    end process;


    ap_condition_712_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_712 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_8));
    end process;


    ap_condition_715_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_715 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_9));
    end process;


    ap_condition_718_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_718 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_9));
    end process;


    ap_condition_721_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_721 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_A));
    end process;


    ap_condition_724_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_724 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_A));
    end process;


    ap_condition_727_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_727 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_B));
    end process;


    ap_condition_730_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_730 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_B));
    end process;


    ap_condition_733_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_733 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_C));
    end process;


    ap_condition_736_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_736 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_C));
    end process;


    ap_condition_739_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_739 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_D));
    end process;


    ap_condition_742_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_742 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_D));
    end process;


    ap_condition_745_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_745 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_E));
    end process;


    ap_condition_748_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_748 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_E));
    end process;


    ap_condition_751_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_751 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_F)) or ((icmp_ln153_reg_2577 = ap_const_lv1_0) and (trunc_ln151_reg_2573 = ap_const_lv4_0))));
    end process;


    ap_condition_754_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln151_reg_2573, icmp_ln153_reg_2577)
    begin
                ap_condition_754 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln153_reg_2577 = ap_const_lv1_1) and (trunc_ln151_reg_2573 = ap_const_lv4_F));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln151_fu_1387_p2)
    begin
        if (((icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_t_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_fu_284, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_t_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_t_1 <= t_fu_284;
        end if; 
    end process;

    bias_buf_16_out <= bias_buf_16_fu_288;

    bias_buf_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_16_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_17_out <= bias_buf_17_fu_300;

    bias_buf_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_17_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_18_out <= bias_buf_18_fu_304;

    bias_buf_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_18_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_19_out <= bias_buf_19_fu_308;

    bias_buf_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_19_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_20_out <= bias_buf_20_fu_312;

    bias_buf_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_20_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_21_out <= bias_buf_21_fu_316;

    bias_buf_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_21_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_22_out <= bias_buf_22_fu_320;

    bias_buf_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_22_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_23_out <= bias_buf_23_fu_324;

    bias_buf_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_23_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_24_out <= bias_buf_24_fu_328;

    bias_buf_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_24_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_25_out <= bias_buf_25_fu_332;

    bias_buf_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_25_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_26_out <= bias_buf_26_fu_336;

    bias_buf_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_26_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_27_out <= bias_buf_27_fu_340;

    bias_buf_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_27_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_28_out <= bias_buf_28_fu_344;

    bias_buf_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_28_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_29_out <= bias_buf_29_fu_348;

    bias_buf_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_29_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_30_out <= bias_buf_30_fu_352;

    bias_buf_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_30_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_31_out <= bias_buf_31_fu_356;

    bias_buf_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_31_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_32_fu_1726_p1 <= qp_mem_Dout_A(32 - 1 downto 0);
    icmp_ln151_fu_1387_p2 <= "1" when (ap_sig_allocacmp_t_1 = ap_const_lv5_10) else "0";
    icmp_ln153_fu_1407_p2 <= "1" when (unsigned(ap_sig_allocacmp_t_1) < unsigned(oc_valid)) else "0";
    m0_buf_16_out <= m0_buf_16_fu_292;

    m0_buf_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_16_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_17_out <= m0_buf_17_fu_360;

    m0_buf_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_17_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_18_out <= m0_buf_18_fu_364;

    m0_buf_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_18_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_19_out <= m0_buf_19_fu_368;

    m0_buf_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_19_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_20_out <= m0_buf_20_fu_372;

    m0_buf_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_20_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_21_out <= m0_buf_21_fu_376;

    m0_buf_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_21_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_22_out <= m0_buf_22_fu_380;

    m0_buf_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_22_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_23_out <= m0_buf_23_fu_384;

    m0_buf_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_23_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_24_out <= m0_buf_24_fu_388;

    m0_buf_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_24_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_25_out <= m0_buf_25_fu_392;

    m0_buf_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_25_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_26_out <= m0_buf_26_fu_396;

    m0_buf_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_26_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_27_out <= m0_buf_27_fu_400;

    m0_buf_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_27_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_28_out <= m0_buf_28_fu_404;

    m0_buf_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_28_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_29_out <= m0_buf_29_fu_408;

    m0_buf_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_29_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_30_out <= m0_buf_30_fu_412;

    m0_buf_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_30_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_31_out <= m0_buf_31_fu_416;

    m0_buf_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_31_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_16_out <= nshift_buf_16_fu_296;

    nshift_buf_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_16_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_17_out <= nshift_buf_17_fu_420;

    nshift_buf_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_17_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_18_out <= nshift_buf_18_fu_424;

    nshift_buf_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_18_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_19_out <= nshift_buf_19_fu_428;

    nshift_buf_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_19_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_20_out <= nshift_buf_20_fu_432;

    nshift_buf_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_20_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_21_out <= nshift_buf_21_fu_436;

    nshift_buf_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_21_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_22_out <= nshift_buf_22_fu_440;

    nshift_buf_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_22_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_23_out <= nshift_buf_23_fu_444;

    nshift_buf_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_23_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_24_out <= nshift_buf_24_fu_448;

    nshift_buf_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_24_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_25_out <= nshift_buf_25_fu_452;

    nshift_buf_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_25_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_26_out <= nshift_buf_26_fu_456;

    nshift_buf_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_26_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_27_out <= nshift_buf_27_fu_460;

    nshift_buf_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_27_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_28_out <= nshift_buf_28_fu_464;

    nshift_buf_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_28_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_29_out <= nshift_buf_29_fu_468;

    nshift_buf_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_29_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_30_out <= nshift_buf_30_fu_472;

    nshift_buf_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_30_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_31_out <= nshift_buf_31_fu_476;

    nshift_buf_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln151_fu_1387_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln151_fu_1387_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_31_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_32_fu_1738_p3 <= qp_mem_Dout_A(69 downto 64);
    qp_mem_Addr_A <= qp_mem_Addr_A_local;
    qp_mem_Addr_A_local <= std_logic_vector(shift_left(unsigned(qp_mem_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    qp_mem_Addr_A_orig <= zext_ln156_fu_1457_p1(32 - 1 downto 0);
    qp_mem_Din_A <= ap_const_lv128_lc_1;
    qp_mem_EN_A <= qp_mem_EN_A_local;

    qp_mem_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            qp_mem_EN_A_local <= ap_const_logic_1;
        else 
            qp_mem_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    qp_mem_WEN_A <= ap_const_lv16_0;
    trunc_ln151_fu_1403_p1 <= ap_sig_allocacmp_t_1(4 - 1 downto 0);
    zext_ln151_1_fu_1399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_t_1),10));
    zext_ln151_cast_fu_1135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln151),10));
    zext_ln156_fu_1457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln156_1_fu_1451_p2),64));
    zext_ln159_fu_1746_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nshift_buf_32_fu_1738_p3),8));
end behav;
