-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    nshift_buf_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf : IN STD_LOGIC_VECTOR (7 downto 0);
    m0_buf_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    m0_buf : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bias_buf : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (9 downto 0);
    shl_ln : IN STD_LOGIC_VECTOR (9 downto 0);
    qp_mem_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    qp_mem_EN_A : OUT STD_LOGIC;
    qp_mem_WEN_A : OUT STD_LOGIC_VECTOR (15 downto 0);
    qp_mem_Din_A : OUT STD_LOGIC_VECTOR (127 downto 0);
    qp_mem_Dout_A : IN STD_LOGIC_VECTOR (127 downto 0);
    oc_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    nshift_buf_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_15_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_14_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_13_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_12_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_11_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_10_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_9_out_ap_vld : OUT STD_LOGIC;
    nshift_buf_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    nshift_buf_8_out_ap_vld : OUT STD_LOGIC;
    m0_buf_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_15_out_ap_vld : OUT STD_LOGIC;
    m0_buf_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_14_out_ap_vld : OUT STD_LOGIC;
    m0_buf_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_13_out_ap_vld : OUT STD_LOGIC;
    m0_buf_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_12_out_ap_vld : OUT STD_LOGIC;
    m0_buf_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_11_out_ap_vld : OUT STD_LOGIC;
    m0_buf_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_10_out_ap_vld : OUT STD_LOGIC;
    m0_buf_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_9_out_ap_vld : OUT STD_LOGIC;
    m0_buf_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    m0_buf_8_out_ap_vld : OUT STD_LOGIC;
    bias_buf_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_15_out_ap_vld : OUT STD_LOGIC;
    bias_buf_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_14_out_ap_vld : OUT STD_LOGIC;
    bias_buf_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_13_out_ap_vld : OUT STD_LOGIC;
    bias_buf_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_12_out_ap_vld : OUT STD_LOGIC;
    bias_buf_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_11_out_ap_vld : OUT STD_LOGIC;
    bias_buf_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_10_out_ap_vld : OUT STD_LOGIC;
    bias_buf_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_9_out_ap_vld : OUT STD_LOGIC;
    bias_buf_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    bias_buf_8_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln118_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal trunc_ln118_fu_778_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln118_reg_1373 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln120_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln120_reg_1377 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln121_fu_801_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal t_fu_170 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln118_fu_764_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_t_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal bias_buf_8_fu_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_16_fu_931_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bias_buf_9_fu_178 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_10_fu_182 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_11_fu_186 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_12_fu_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_13_fu_194 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_14_fu_198 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bias_buf_15_fu_202 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_8_fu_206 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_9_fu_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_10_fu_214 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_11_fu_218 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_12_fu_222 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_13_fu_226 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_14_fu_230 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal m0_buf_15_fu_234 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal nshift_buf_8_fu_238 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zext_ln124_fu_951_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal nshift_buf_9_fu_242 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_10_fu_246 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_11_fu_250 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_12_fu_254 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_13_fu_258 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_14_fu_262 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal nshift_buf_15_fu_266 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal qp_mem_EN_A_local : STD_LOGIC;
    signal qp_mem_Addr_A_local : STD_LOGIC_VECTOR (31 downto 0);
    signal qp_mem_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln118_1_fu_774_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln118_fu_770_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln121_fu_789_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln121_1_fu_795_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal bias_buf_16_fu_931_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal m0_buf_16_fu_935_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal nshift_buf_16_fu_943_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal nshift_buf_16_fu_943_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_432 : BOOLEAN;
    signal ap_condition_436 : BOOLEAN;
    signal ap_condition_439 : BOOLEAN;
    signal ap_condition_442 : BOOLEAN;
    signal ap_condition_445 : BOOLEAN;
    signal ap_condition_448 : BOOLEAN;
    signal ap_condition_451 : BOOLEAN;
    signal ap_condition_454 : BOOLEAN;
    signal ap_condition_457 : BOOLEAN;
    signal ap_condition_460 : BOOLEAN;
    signal ap_condition_463 : BOOLEAN;
    signal ap_condition_466 : BOOLEAN;
    signal ap_condition_469 : BOOLEAN;
    signal ap_condition_472 : BOOLEAN;
    signal ap_condition_475 : BOOLEAN;
    signal ap_condition_478 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component tinyissimo_layer_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    bias_buf_10_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_10_fu_182 <= bias_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_436)) then 
                    bias_buf_10_fu_182 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_432)) then 
                    bias_buf_10_fu_182 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_11_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_11_fu_186 <= bias_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_442)) then 
                    bias_buf_11_fu_186 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_439)) then 
                    bias_buf_11_fu_186 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_12_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_12_fu_190 <= bias_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_448)) then 
                    bias_buf_12_fu_190 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_445)) then 
                    bias_buf_12_fu_190 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_13_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_13_fu_194 <= bias_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_454)) then 
                    bias_buf_13_fu_194 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_451)) then 
                    bias_buf_13_fu_194 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_14_fu_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_14_fu_198 <= bias_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_460)) then 
                    bias_buf_14_fu_198 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_457)) then 
                    bias_buf_14_fu_198 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_15_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_15_fu_202 <= bias_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_466)) then 
                    bias_buf_15_fu_202 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_463)) then 
                    bias_buf_15_fu_202 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_8_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_8_fu_174 <= bias_buf;
                elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                    bias_buf_8_fu_174 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_469)) then 
                    bias_buf_8_fu_174 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    bias_buf_9_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    bias_buf_9_fu_178 <= bias_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_478)) then 
                    bias_buf_9_fu_178 <= bias_buf_16_fu_931_p1;
                elsif ((ap_const_boolean_1 = ap_condition_475)) then 
                    bias_buf_9_fu_178 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_10_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_10_fu_214 <= m0_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_436)) then 
                    m0_buf_10_fu_214 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_432)) then 
                    m0_buf_10_fu_214 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_11_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_11_fu_218 <= m0_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_442)) then 
                    m0_buf_11_fu_218 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_439)) then 
                    m0_buf_11_fu_218 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_12_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_12_fu_222 <= m0_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_448)) then 
                    m0_buf_12_fu_222 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_445)) then 
                    m0_buf_12_fu_222 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_13_fu_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_13_fu_226 <= m0_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_454)) then 
                    m0_buf_13_fu_226 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_451)) then 
                    m0_buf_13_fu_226 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_14_fu_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_14_fu_230 <= m0_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_460)) then 
                    m0_buf_14_fu_230 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_457)) then 
                    m0_buf_14_fu_230 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_15_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_15_fu_234 <= m0_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_466)) then 
                    m0_buf_15_fu_234 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_463)) then 
                    m0_buf_15_fu_234 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_8_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_8_fu_206 <= m0_buf;
                elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                    m0_buf_8_fu_206 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_469)) then 
                    m0_buf_8_fu_206 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    m0_buf_9_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    m0_buf_9_fu_210 <= m0_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_478)) then 
                    m0_buf_9_fu_210 <= m0_buf_16_fu_935_p1(63 downto 32);
                elsif ((ap_const_boolean_1 = ap_condition_475)) then 
                    m0_buf_9_fu_210 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_10_fu_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_10_fu_246 <= nshift_buf_2;
                elsif ((ap_const_boolean_1 = ap_condition_436)) then 
                    nshift_buf_10_fu_246 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_432)) then 
                    nshift_buf_10_fu_246 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_11_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_11_fu_250 <= nshift_buf_3;
                elsif ((ap_const_boolean_1 = ap_condition_442)) then 
                    nshift_buf_11_fu_250 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_439)) then 
                    nshift_buf_11_fu_250 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_12_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_12_fu_254 <= nshift_buf_4;
                elsif ((ap_const_boolean_1 = ap_condition_448)) then 
                    nshift_buf_12_fu_254 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_445)) then 
                    nshift_buf_12_fu_254 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_13_fu_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_13_fu_258 <= nshift_buf_5;
                elsif ((ap_const_boolean_1 = ap_condition_454)) then 
                    nshift_buf_13_fu_258 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_451)) then 
                    nshift_buf_13_fu_258 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_14_fu_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_14_fu_262 <= nshift_buf_6;
                elsif ((ap_const_boolean_1 = ap_condition_460)) then 
                    nshift_buf_14_fu_262 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_457)) then 
                    nshift_buf_14_fu_262 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_15_fu_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_15_fu_266 <= nshift_buf_7;
                elsif ((ap_const_boolean_1 = ap_condition_466)) then 
                    nshift_buf_15_fu_266 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_463)) then 
                    nshift_buf_15_fu_266 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_8_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_8_fu_238 <= nshift_buf;
                elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                    nshift_buf_8_fu_238 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_469)) then 
                    nshift_buf_8_fu_238 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    nshift_buf_9_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    nshift_buf_9_fu_242 <= nshift_buf_1;
                elsif ((ap_const_boolean_1 = ap_condition_478)) then 
                    nshift_buf_9_fu_242 <= zext_ln124_fu_951_p1;
                elsif ((ap_const_boolean_1 = ap_condition_475)) then 
                    nshift_buf_9_fu_242 <= ap_const_lv8_1;
                end if;
            end if; 
        end if;
    end process;

    t_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln118_fu_758_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_170 <= add_ln118_fu_764_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_170 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln120_reg_1377 <= icmp_ln120_fu_783_p2;
                trunc_ln118_reg_1373 <= trunc_ln118_fu_778_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln118_fu_764_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_1) + unsigned(ap_const_lv4_1));
    add_ln121_1_fu_795_p2 <= std_logic_vector(unsigned(add_ln121_fu_789_p2) + unsigned(shl_ln));
    add_ln121_fu_789_p2 <= std_logic_vector(unsigned(zext_ln118_fu_770_p1) + unsigned(empty));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_432_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_432 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_2));
    end process;


    ap_condition_436_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_436 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_2));
    end process;


    ap_condition_439_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_439 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_3));
    end process;


    ap_condition_442_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_442 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_3));
    end process;


    ap_condition_445_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_445 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_4));
    end process;


    ap_condition_448_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_448 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_4));
    end process;


    ap_condition_451_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_451 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_5));
    end process;


    ap_condition_454_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_454 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_5));
    end process;


    ap_condition_457_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_457 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_6));
    end process;


    ap_condition_460_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_460 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_6));
    end process;


    ap_condition_463_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_463 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_7));
    end process;


    ap_condition_466_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_466 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_7));
    end process;


    ap_condition_469_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_469 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_0));
    end process;


    ap_condition_472_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_472 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_0));
    end process;


    ap_condition_475_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_475 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_0) and (trunc_ln118_reg_1373 = ap_const_lv3_1));
    end process;


    ap_condition_478_assign_proc : process(ap_enable_reg_pp0_iter1, trunc_ln118_reg_1373, icmp_ln120_reg_1377)
    begin
                ap_condition_478 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln120_reg_1377 = ap_const_lv1_1) and (trunc_ln118_reg_1373 = ap_const_lv3_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln118_fu_758_p2)
    begin
        if (((icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_t_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_fu_170, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_t_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_t_1 <= t_fu_170;
        end if; 
    end process;

    bias_buf_10_out <= bias_buf_10_fu_182;

    bias_buf_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_10_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_11_out <= bias_buf_11_fu_186;

    bias_buf_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_11_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_12_out <= bias_buf_12_fu_190;

    bias_buf_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_12_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_13_out <= bias_buf_13_fu_194;

    bias_buf_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_13_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_14_out <= bias_buf_14_fu_198;

    bias_buf_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_14_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_15_out <= bias_buf_15_fu_202;

    bias_buf_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_15_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_16_fu_931_p0 <= qp_mem_Dout_A(72 - 1 downto 0);
    bias_buf_16_fu_931_p1 <= bias_buf_16_fu_931_p0(32 - 1 downto 0);
    bias_buf_8_out <= bias_buf_8_fu_174;

    bias_buf_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_8_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    bias_buf_9_out <= bias_buf_9_fu_178;

    bias_buf_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_buf_9_out_ap_vld <= ap_const_logic_1;
        else 
            bias_buf_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln118_fu_758_p2 <= "1" when (ap_sig_allocacmp_t_1 = ap_const_lv4_8) else "0";
    icmp_ln120_fu_783_p2 <= "1" when (signed(zext_ln118_1_fu_774_p1) < signed(oc_valid)) else "0";
    m0_buf_10_out <= m0_buf_10_fu_214;

    m0_buf_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_10_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_11_out <= m0_buf_11_fu_218;

    m0_buf_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_11_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_12_out <= m0_buf_12_fu_222;

    m0_buf_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_12_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_13_out <= m0_buf_13_fu_226;

    m0_buf_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_13_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_14_out <= m0_buf_14_fu_230;

    m0_buf_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_14_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_15_out <= m0_buf_15_fu_234;

    m0_buf_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_15_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_16_fu_935_p1 <= qp_mem_Dout_A(72 - 1 downto 0);
    m0_buf_8_out <= m0_buf_8_fu_206;

    m0_buf_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_8_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    m0_buf_9_out <= m0_buf_9_fu_210;

    m0_buf_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m0_buf_9_out_ap_vld <= ap_const_logic_1;
        else 
            m0_buf_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_10_out <= nshift_buf_10_fu_246;

    nshift_buf_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_10_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_11_out <= nshift_buf_11_fu_250;

    nshift_buf_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_11_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_12_out <= nshift_buf_12_fu_254;

    nshift_buf_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_12_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_13_out <= nshift_buf_13_fu_258;

    nshift_buf_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_13_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_14_out <= nshift_buf_14_fu_262;

    nshift_buf_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_14_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_15_out <= nshift_buf_15_fu_266;

    nshift_buf_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_15_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_16_fu_943_p1 <= qp_mem_Dout_A(72 - 1 downto 0);
    nshift_buf_16_fu_943_p3 <= nshift_buf_16_fu_943_p1(69 downto 64);
    nshift_buf_8_out <= nshift_buf_8_fu_238;

    nshift_buf_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_8_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    nshift_buf_9_out <= nshift_buf_9_fu_242;

    nshift_buf_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln118_fu_758_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln118_fu_758_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nshift_buf_9_out_ap_vld <= ap_const_logic_1;
        else 
            nshift_buf_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    qp_mem_Addr_A <= qp_mem_Addr_A_local;
    qp_mem_Addr_A_local <= std_logic_vector(shift_left(unsigned(qp_mem_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    qp_mem_Addr_A_orig <= zext_ln121_fu_801_p1(32 - 1 downto 0);
    qp_mem_Din_A <= ap_const_lv128_lc_1;
    qp_mem_EN_A <= qp_mem_EN_A_local;

    qp_mem_EN_A_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            qp_mem_EN_A_local <= ap_const_logic_1;
        else 
            qp_mem_EN_A_local <= ap_const_logic_0;
        end if; 
    end process;

    qp_mem_WEN_A <= ap_const_lv16_0;
    trunc_ln118_fu_778_p1 <= ap_sig_allocacmp_t_1(3 - 1 downto 0);
    zext_ln118_1_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_t_1),5));
    zext_ln118_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_t_1),10));
    zext_ln121_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln121_1_fu_795_p2),64));
    zext_ln124_fu_951_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(nshift_buf_16_fu_943_p3),8));
end behav;
