// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        nshift_buf_7,
        nshift_buf_6,
        nshift_buf_5,
        nshift_buf_4,
        nshift_buf_3,
        nshift_buf_2,
        nshift_buf_1,
        nshift_buf,
        m0_buf_7,
        m0_buf_6,
        m0_buf_5,
        m0_buf_4,
        m0_buf_3,
        m0_buf_2,
        m0_buf_1,
        m0_buf,
        bias_buf_7,
        bias_buf_6,
        bias_buf_5,
        bias_buf_4,
        bias_buf_3,
        bias_buf_2,
        bias_buf_1,
        bias_buf,
        cfg_qp_base,
        zext_ln130_1,
        qp_mem_Addr_A,
        qp_mem_EN_A,
        qp_mem_WEN_A,
        qp_mem_Din_A,
        qp_mem_Dout_A,
        oc_valid,
        nshift_buf_23_out,
        nshift_buf_23_out_ap_vld,
        nshift_buf_22_out,
        nshift_buf_22_out_ap_vld,
        nshift_buf_21_out,
        nshift_buf_21_out_ap_vld,
        nshift_buf_20_out,
        nshift_buf_20_out_ap_vld,
        nshift_buf_19_out,
        nshift_buf_19_out_ap_vld,
        nshift_buf_18_out,
        nshift_buf_18_out_ap_vld,
        nshift_buf_17_out,
        nshift_buf_17_out_ap_vld,
        nshift_buf_16_out,
        nshift_buf_16_out_ap_vld,
        m0_buf_23_out,
        m0_buf_23_out_ap_vld,
        m0_buf_22_out,
        m0_buf_22_out_ap_vld,
        m0_buf_21_out,
        m0_buf_21_out_ap_vld,
        m0_buf_20_out,
        m0_buf_20_out_ap_vld,
        m0_buf_19_out,
        m0_buf_19_out_ap_vld,
        m0_buf_18_out,
        m0_buf_18_out_ap_vld,
        m0_buf_17_out,
        m0_buf_17_out_ap_vld,
        m0_buf_16_out,
        m0_buf_16_out_ap_vld,
        bias_buf_23_out,
        bias_buf_23_out_ap_vld,
        bias_buf_22_out,
        bias_buf_22_out_ap_vld,
        bias_buf_21_out,
        bias_buf_21_out_ap_vld,
        bias_buf_20_out,
        bias_buf_20_out_ap_vld,
        bias_buf_19_out,
        bias_buf_19_out_ap_vld,
        bias_buf_18_out,
        bias_buf_18_out_ap_vld,
        bias_buf_17_out,
        bias_buf_17_out_ap_vld,
        bias_buf_16_out,
        bias_buf_16_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] nshift_buf_7;
input  [7:0] nshift_buf_6;
input  [7:0] nshift_buf_5;
input  [7:0] nshift_buf_4;
input  [7:0] nshift_buf_3;
input  [7:0] nshift_buf_2;
input  [7:0] nshift_buf_1;
input  [7:0] nshift_buf;
input  [31:0] m0_buf_7;
input  [31:0] m0_buf_6;
input  [31:0] m0_buf_5;
input  [31:0] m0_buf_4;
input  [31:0] m0_buf_3;
input  [31:0] m0_buf_2;
input  [31:0] m0_buf_1;
input  [31:0] m0_buf;
input  [31:0] bias_buf_7;
input  [31:0] bias_buf_6;
input  [31:0] bias_buf_5;
input  [31:0] bias_buf_4;
input  [31:0] bias_buf_3;
input  [31:0] bias_buf_2;
input  [31:0] bias_buf_1;
input  [31:0] bias_buf;
input  [9:0] cfg_qp_base;
input  [6:0] zext_ln130_1;
output  [31:0] qp_mem_Addr_A;
output   qp_mem_EN_A;
output  [15:0] qp_mem_WEN_A;
output  [127:0] qp_mem_Din_A;
input  [127:0] qp_mem_Dout_A;
input  [3:0] oc_valid;
output  [7:0] nshift_buf_23_out;
output   nshift_buf_23_out_ap_vld;
output  [7:0] nshift_buf_22_out;
output   nshift_buf_22_out_ap_vld;
output  [7:0] nshift_buf_21_out;
output   nshift_buf_21_out_ap_vld;
output  [7:0] nshift_buf_20_out;
output   nshift_buf_20_out_ap_vld;
output  [7:0] nshift_buf_19_out;
output   nshift_buf_19_out_ap_vld;
output  [7:0] nshift_buf_18_out;
output   nshift_buf_18_out_ap_vld;
output  [7:0] nshift_buf_17_out;
output   nshift_buf_17_out_ap_vld;
output  [7:0] nshift_buf_16_out;
output   nshift_buf_16_out_ap_vld;
output  [31:0] m0_buf_23_out;
output   m0_buf_23_out_ap_vld;
output  [31:0] m0_buf_22_out;
output   m0_buf_22_out_ap_vld;
output  [31:0] m0_buf_21_out;
output   m0_buf_21_out_ap_vld;
output  [31:0] m0_buf_20_out;
output   m0_buf_20_out_ap_vld;
output  [31:0] m0_buf_19_out;
output   m0_buf_19_out_ap_vld;
output  [31:0] m0_buf_18_out;
output   m0_buf_18_out_ap_vld;
output  [31:0] m0_buf_17_out;
output   m0_buf_17_out_ap_vld;
output  [31:0] m0_buf_16_out;
output   m0_buf_16_out_ap_vld;
output  [31:0] bias_buf_23_out;
output   bias_buf_23_out_ap_vld;
output  [31:0] bias_buf_22_out;
output   bias_buf_22_out_ap_vld;
output  [31:0] bias_buf_21_out;
output   bias_buf_21_out_ap_vld;
output  [31:0] bias_buf_20_out;
output   bias_buf_20_out_ap_vld;
output  [31:0] bias_buf_19_out;
output   bias_buf_19_out_ap_vld;
output  [31:0] bias_buf_18_out;
output   bias_buf_18_out_ap_vld;
output  [31:0] bias_buf_17_out;
output   bias_buf_17_out_ap_vld;
output  [31:0] bias_buf_16_out;
output   bias_buf_16_out_ap_vld;

reg ap_idle;
reg nshift_buf_23_out_ap_vld;
reg nshift_buf_22_out_ap_vld;
reg nshift_buf_21_out_ap_vld;
reg nshift_buf_20_out_ap_vld;
reg nshift_buf_19_out_ap_vld;
reg nshift_buf_18_out_ap_vld;
reg nshift_buf_17_out_ap_vld;
reg nshift_buf_16_out_ap_vld;
reg m0_buf_23_out_ap_vld;
reg m0_buf_22_out_ap_vld;
reg m0_buf_21_out_ap_vld;
reg m0_buf_20_out_ap_vld;
reg m0_buf_19_out_ap_vld;
reg m0_buf_18_out_ap_vld;
reg m0_buf_17_out_ap_vld;
reg m0_buf_16_out_ap_vld;
reg bias_buf_23_out_ap_vld;
reg bias_buf_22_out_ap_vld;
reg bias_buf_21_out_ap_vld;
reg bias_buf_20_out_ap_vld;
reg bias_buf_19_out_ap_vld;
reg bias_buf_18_out_ap_vld;
reg bias_buf_17_out_ap_vld;
reg bias_buf_16_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln130_fu_747_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] trunc_ln130_fu_763_p1;
reg   [2:0] trunc_ln130_reg_1373;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln132_fu_767_p2;
reg   [0:0] icmp_ln132_reg_1377;
wire   [63:0] zext_ln135_fu_801_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] t_fu_172;
wire   [3:0] add_ln130_fu_753_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_t_2;
reg   [31:0] bias_buf_16_fu_176;
wire   [31:0] bias_buf_24_fu_934_p1;
reg   [31:0] m0_buf_16_fu_180;
reg   [7:0] nshift_buf_16_fu_184;
wire   [7:0] zext_ln138_fu_954_p1;
reg   [31:0] bias_buf_17_fu_188;
reg   [31:0] bias_buf_18_fu_192;
reg   [31:0] bias_buf_19_fu_196;
reg   [31:0] bias_buf_20_fu_200;
reg   [31:0] bias_buf_21_fu_204;
reg   [31:0] bias_buf_22_fu_208;
reg   [31:0] bias_buf_23_fu_212;
reg   [31:0] m0_buf_17_fu_216;
reg   [31:0] m0_buf_18_fu_220;
reg   [31:0] m0_buf_19_fu_224;
reg   [31:0] m0_buf_20_fu_228;
reg   [31:0] m0_buf_21_fu_232;
reg   [31:0] m0_buf_22_fu_236;
reg   [31:0] m0_buf_23_fu_240;
reg   [7:0] nshift_buf_17_fu_244;
reg   [7:0] nshift_buf_18_fu_248;
reg   [7:0] nshift_buf_19_fu_252;
reg   [7:0] nshift_buf_20_fu_256;
reg   [7:0] nshift_buf_21_fu_260;
reg   [7:0] nshift_buf_22_fu_264;
reg   [7:0] nshift_buf_23_fu_268;
wire    ap_block_pp0_stage0_01001;
reg    qp_mem_EN_A_local;
wire   [31:0] qp_mem_Addr_A_local;
wire   [31:0] qp_mem_Addr_A_orig;
wire   [9:0] zext_ln130_fu_759_p1;
wire   [9:0] add_ln135_fu_789_p2;
wire   [9:0] zext_ln130_1_cast_fu_615_p1;
wire   [9:0] add_ln135_2_fu_795_p2;
wire   [5:0] nshift_buf_24_fu_946_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_431;
reg    ap_condition_435;
reg    ap_condition_438;
reg    ap_condition_441;
reg    ap_condition_444;
reg    ap_condition_447;
reg    ap_condition_450;
reg    ap_condition_453;
reg    ap_condition_456;
reg    ap_condition_459;
reg    ap_condition_462;
reg    ap_condition_465;
reg    ap_condition_468;
reg    ap_condition_471;
reg    ap_condition_474;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 t_fu_172 = 4'd0;
#0 bias_buf_16_fu_176 = 32'd0;
#0 m0_buf_16_fu_180 = 32'd0;
#0 nshift_buf_16_fu_184 = 8'd0;
#0 bias_buf_17_fu_188 = 32'd0;
#0 bias_buf_18_fu_192 = 32'd0;
#0 bias_buf_19_fu_196 = 32'd0;
#0 bias_buf_20_fu_200 = 32'd0;
#0 bias_buf_21_fu_204 = 32'd0;
#0 bias_buf_22_fu_208 = 32'd0;
#0 bias_buf_23_fu_212 = 32'd0;
#0 m0_buf_17_fu_216 = 32'd0;
#0 m0_buf_18_fu_220 = 32'd0;
#0 m0_buf_19_fu_224 = 32'd0;
#0 m0_buf_20_fu_228 = 32'd0;
#0 m0_buf_21_fu_232 = 32'd0;
#0 m0_buf_22_fu_236 = 32'd0;
#0 m0_buf_23_fu_240 = 32'd0;
#0 nshift_buf_17_fu_244 = 8'd0;
#0 nshift_buf_18_fu_248 = 8'd0;
#0 nshift_buf_19_fu_252 = 8'd0;
#0 nshift_buf_20_fu_256 = 8'd0;
#0 nshift_buf_21_fu_260 = 8'd0;
#0 nshift_buf_22_fu_264 = 8'd0;
#0 nshift_buf_23_fu_268 = 8'd0;
#0 ap_done_reg = 1'b0;
end

tinyissimo_layer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_16_fu_176 <= bias_buf;
        end else if ((1'b1 == ap_condition_431)) begin
            bias_buf_16_fu_176 <= bias_buf_24_fu_934_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_17_fu_188 <= bias_buf_1;
        end else if ((1'b1 == ap_condition_438)) begin
            bias_buf_17_fu_188 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_435)) begin
            bias_buf_17_fu_188 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_18_fu_192 <= bias_buf_2;
        end else if ((1'b1 == ap_condition_444)) begin
            bias_buf_18_fu_192 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_441)) begin
            bias_buf_18_fu_192 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_19_fu_196 <= bias_buf_3;
        end else if ((1'b1 == ap_condition_450)) begin
            bias_buf_19_fu_196 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_447)) begin
            bias_buf_19_fu_196 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_20_fu_200 <= bias_buf_4;
        end else if ((1'b1 == ap_condition_456)) begin
            bias_buf_20_fu_200 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_453)) begin
            bias_buf_20_fu_200 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_21_fu_204 <= bias_buf_5;
        end else if ((1'b1 == ap_condition_462)) begin
            bias_buf_21_fu_204 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_459)) begin
            bias_buf_21_fu_204 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_22_fu_208 <= bias_buf_6;
        end else if ((1'b1 == ap_condition_468)) begin
            bias_buf_22_fu_208 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_465)) begin
            bias_buf_22_fu_208 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_23_fu_212 <= bias_buf_7;
        end else if ((1'b1 == ap_condition_474)) begin
            bias_buf_23_fu_212 <= bias_buf_24_fu_934_p1;
        end else if ((1'b1 == ap_condition_471)) begin
            bias_buf_23_fu_212 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_16_fu_180 <= m0_buf;
        end else if ((1'b1 == ap_condition_431)) begin
            m0_buf_16_fu_180 <= {{qp_mem_Dout_A[63:32]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_17_fu_216 <= m0_buf_1;
        end else if ((1'b1 == ap_condition_438)) begin
            m0_buf_17_fu_216 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_435)) begin
            m0_buf_17_fu_216 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_18_fu_220 <= m0_buf_2;
        end else if ((1'b1 == ap_condition_444)) begin
            m0_buf_18_fu_220 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_441)) begin
            m0_buf_18_fu_220 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_19_fu_224 <= m0_buf_3;
        end else if ((1'b1 == ap_condition_450)) begin
            m0_buf_19_fu_224 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_447)) begin
            m0_buf_19_fu_224 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_20_fu_228 <= m0_buf_4;
        end else if ((1'b1 == ap_condition_456)) begin
            m0_buf_20_fu_228 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_453)) begin
            m0_buf_20_fu_228 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_21_fu_232 <= m0_buf_5;
        end else if ((1'b1 == ap_condition_462)) begin
            m0_buf_21_fu_232 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_459)) begin
            m0_buf_21_fu_232 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_22_fu_236 <= m0_buf_6;
        end else if ((1'b1 == ap_condition_468)) begin
            m0_buf_22_fu_236 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_465)) begin
            m0_buf_22_fu_236 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_23_fu_240 <= m0_buf_7;
        end else if ((1'b1 == ap_condition_474)) begin
            m0_buf_23_fu_240 <= {{qp_mem_Dout_A[63:32]}};
        end else if ((1'b1 == ap_condition_471)) begin
            m0_buf_23_fu_240 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_16_fu_184 <= nshift_buf;
        end else if ((1'b1 == ap_condition_431)) begin
            nshift_buf_16_fu_184 <= zext_ln138_fu_954_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_17_fu_244 <= nshift_buf_1;
        end else if ((1'b1 == ap_condition_438)) begin
            nshift_buf_17_fu_244 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_435)) begin
            nshift_buf_17_fu_244 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_18_fu_248 <= nshift_buf_2;
        end else if ((1'b1 == ap_condition_444)) begin
            nshift_buf_18_fu_248 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_441)) begin
            nshift_buf_18_fu_248 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_19_fu_252 <= nshift_buf_3;
        end else if ((1'b1 == ap_condition_450)) begin
            nshift_buf_19_fu_252 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_447)) begin
            nshift_buf_19_fu_252 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_20_fu_256 <= nshift_buf_4;
        end else if ((1'b1 == ap_condition_456)) begin
            nshift_buf_20_fu_256 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_453)) begin
            nshift_buf_20_fu_256 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_21_fu_260 <= nshift_buf_5;
        end else if ((1'b1 == ap_condition_462)) begin
            nshift_buf_21_fu_260 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_459)) begin
            nshift_buf_21_fu_260 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_22_fu_264 <= nshift_buf_6;
        end else if ((1'b1 == ap_condition_468)) begin
            nshift_buf_22_fu_264 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_465)) begin
            nshift_buf_22_fu_264 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_23_fu_268 <= nshift_buf_7;
        end else if ((1'b1 == ap_condition_474)) begin
            nshift_buf_23_fu_268 <= zext_ln138_fu_954_p1;
        end else if ((1'b1 == ap_condition_471)) begin
            nshift_buf_23_fu_268 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln130_fu_747_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_172 <= add_ln130_fu_753_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_172 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln132_reg_1377 <= icmp_ln132_fu_767_p2;
        trunc_ln130_reg_1373 <= trunc_ln130_fu_763_p1;
    end
end

always @ (*) begin
    if (((icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_t_2 = t_fu_172;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_16_out_ap_vld = 1'b1;
    end else begin
        bias_buf_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_17_out_ap_vld = 1'b1;
    end else begin
        bias_buf_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_18_out_ap_vld = 1'b1;
    end else begin
        bias_buf_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_19_out_ap_vld = 1'b1;
    end else begin
        bias_buf_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_20_out_ap_vld = 1'b1;
    end else begin
        bias_buf_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_21_out_ap_vld = 1'b1;
    end else begin
        bias_buf_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_22_out_ap_vld = 1'b1;
    end else begin
        bias_buf_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_23_out_ap_vld = 1'b1;
    end else begin
        bias_buf_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_16_out_ap_vld = 1'b1;
    end else begin
        m0_buf_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_17_out_ap_vld = 1'b1;
    end else begin
        m0_buf_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_18_out_ap_vld = 1'b1;
    end else begin
        m0_buf_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_19_out_ap_vld = 1'b1;
    end else begin
        m0_buf_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_20_out_ap_vld = 1'b1;
    end else begin
        m0_buf_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_21_out_ap_vld = 1'b1;
    end else begin
        m0_buf_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_22_out_ap_vld = 1'b1;
    end else begin
        m0_buf_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_23_out_ap_vld = 1'b1;
    end else begin
        m0_buf_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_16_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_17_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_18_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_19_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_20_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_21_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_22_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln130_fu_747_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_23_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qp_mem_EN_A_local = 1'b1;
    end else begin
        qp_mem_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln130_fu_753_p2 = (ap_sig_allocacmp_t_2 + 4'd1);

assign add_ln135_2_fu_795_p2 = (add_ln135_fu_789_p2 + zext_ln130_1_cast_fu_615_p1);

assign add_ln135_fu_789_p2 = (zext_ln130_fu_759_p1 + cfg_qp_base);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_431 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd0));
end

always @ (*) begin
    ap_condition_435 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd1));
end

always @ (*) begin
    ap_condition_438 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd1));
end

always @ (*) begin
    ap_condition_441 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd2));
end

always @ (*) begin
    ap_condition_444 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd2));
end

always @ (*) begin
    ap_condition_447 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd3));
end

always @ (*) begin
    ap_condition_450 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd3));
end

always @ (*) begin
    ap_condition_453 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd4));
end

always @ (*) begin
    ap_condition_456 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd4));
end

always @ (*) begin
    ap_condition_459 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd5));
end

always @ (*) begin
    ap_condition_462 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd5));
end

always @ (*) begin
    ap_condition_465 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd6));
end

always @ (*) begin
    ap_condition_468 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd6));
end

always @ (*) begin
    ap_condition_471 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd7)) | ((icmp_ln132_reg_1377 == 1'd0) & (trunc_ln130_reg_1373 == 3'd0))));
end

always @ (*) begin
    ap_condition_474 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln132_reg_1377 == 1'd1) & (trunc_ln130_reg_1373 == 3'd7));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bias_buf_16_out = bias_buf_16_fu_176;

assign bias_buf_17_out = bias_buf_17_fu_188;

assign bias_buf_18_out = bias_buf_18_fu_192;

assign bias_buf_19_out = bias_buf_19_fu_196;

assign bias_buf_20_out = bias_buf_20_fu_200;

assign bias_buf_21_out = bias_buf_21_fu_204;

assign bias_buf_22_out = bias_buf_22_fu_208;

assign bias_buf_23_out = bias_buf_23_fu_212;

assign bias_buf_24_fu_934_p1 = qp_mem_Dout_A[31:0];

assign icmp_ln130_fu_747_p2 = ((ap_sig_allocacmp_t_2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_767_p2 = ((ap_sig_allocacmp_t_2 < oc_valid) ? 1'b1 : 1'b0);

assign m0_buf_16_out = m0_buf_16_fu_180;

assign m0_buf_17_out = m0_buf_17_fu_216;

assign m0_buf_18_out = m0_buf_18_fu_220;

assign m0_buf_19_out = m0_buf_19_fu_224;

assign m0_buf_20_out = m0_buf_20_fu_228;

assign m0_buf_21_out = m0_buf_21_fu_232;

assign m0_buf_22_out = m0_buf_22_fu_236;

assign m0_buf_23_out = m0_buf_23_fu_240;

assign nshift_buf_16_out = nshift_buf_16_fu_184;

assign nshift_buf_17_out = nshift_buf_17_fu_244;

assign nshift_buf_18_out = nshift_buf_18_fu_248;

assign nshift_buf_19_out = nshift_buf_19_fu_252;

assign nshift_buf_20_out = nshift_buf_20_fu_256;

assign nshift_buf_21_out = nshift_buf_21_fu_260;

assign nshift_buf_22_out = nshift_buf_22_fu_264;

assign nshift_buf_23_out = nshift_buf_23_fu_268;

assign nshift_buf_24_fu_946_p3 = {{qp_mem_Dout_A[69:64]}};

assign qp_mem_Addr_A = qp_mem_Addr_A_local;

assign qp_mem_Addr_A_local = qp_mem_Addr_A_orig << 32'd4;

assign qp_mem_Addr_A_orig = zext_ln135_fu_801_p1;

assign qp_mem_Din_A = 128'd0;

assign qp_mem_EN_A = qp_mem_EN_A_local;

assign qp_mem_WEN_A = 16'd0;

assign trunc_ln130_fu_763_p1 = ap_sig_allocacmp_t_2[2:0];

assign zext_ln130_1_cast_fu_615_p1 = zext_ln130_1;

assign zext_ln130_fu_759_p1 = ap_sig_allocacmp_t_2;

assign zext_ln135_fu_801_p1 = add_ln135_2_fu_795_p2;

assign zext_ln138_fu_954_p1 = nshift_buf_24_fu_946_p3;

endmodule //tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP
