// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        nshift_buf_7,
        nshift_buf_6,
        nshift_buf_5,
        nshift_buf_4,
        nshift_buf_3,
        nshift_buf_2,
        nshift_buf_1,
        nshift_buf,
        m0_buf_7,
        m0_buf_6,
        m0_buf_5,
        m0_buf_4,
        m0_buf_3,
        m0_buf_2,
        m0_buf_1,
        m0_buf,
        bias_buf_7,
        bias_buf_6,
        bias_buf_5,
        bias_buf_4,
        bias_buf_3,
        bias_buf_2,
        bias_buf_1,
        bias_buf,
        empty,
        shl_ln,
        qp_mem_Addr_A,
        qp_mem_EN_A,
        qp_mem_WEN_A,
        qp_mem_Din_A,
        qp_mem_Dout_A,
        oc_valid,
        nshift_buf_15_out,
        nshift_buf_15_out_ap_vld,
        nshift_buf_14_out,
        nshift_buf_14_out_ap_vld,
        nshift_buf_13_out,
        nshift_buf_13_out_ap_vld,
        nshift_buf_12_out,
        nshift_buf_12_out_ap_vld,
        nshift_buf_11_out,
        nshift_buf_11_out_ap_vld,
        nshift_buf_10_out,
        nshift_buf_10_out_ap_vld,
        nshift_buf_9_out,
        nshift_buf_9_out_ap_vld,
        nshift_buf_8_out,
        nshift_buf_8_out_ap_vld,
        m0_buf_15_out,
        m0_buf_15_out_ap_vld,
        m0_buf_14_out,
        m0_buf_14_out_ap_vld,
        m0_buf_13_out,
        m0_buf_13_out_ap_vld,
        m0_buf_12_out,
        m0_buf_12_out_ap_vld,
        m0_buf_11_out,
        m0_buf_11_out_ap_vld,
        m0_buf_10_out,
        m0_buf_10_out_ap_vld,
        m0_buf_9_out,
        m0_buf_9_out_ap_vld,
        m0_buf_8_out,
        m0_buf_8_out_ap_vld,
        bias_buf_15_out,
        bias_buf_15_out_ap_vld,
        bias_buf_14_out,
        bias_buf_14_out_ap_vld,
        bias_buf_13_out,
        bias_buf_13_out_ap_vld,
        bias_buf_12_out,
        bias_buf_12_out_ap_vld,
        bias_buf_11_out,
        bias_buf_11_out_ap_vld,
        bias_buf_10_out,
        bias_buf_10_out_ap_vld,
        bias_buf_9_out,
        bias_buf_9_out_ap_vld,
        bias_buf_8_out,
        bias_buf_8_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] nshift_buf_7;
input  [7:0] nshift_buf_6;
input  [7:0] nshift_buf_5;
input  [7:0] nshift_buf_4;
input  [7:0] nshift_buf_3;
input  [7:0] nshift_buf_2;
input  [7:0] nshift_buf_1;
input  [7:0] nshift_buf;
input  [31:0] m0_buf_7;
input  [31:0] m0_buf_6;
input  [31:0] m0_buf_5;
input  [31:0] m0_buf_4;
input  [31:0] m0_buf_3;
input  [31:0] m0_buf_2;
input  [31:0] m0_buf_1;
input  [31:0] m0_buf;
input  [31:0] bias_buf_7;
input  [31:0] bias_buf_6;
input  [31:0] bias_buf_5;
input  [31:0] bias_buf_4;
input  [31:0] bias_buf_3;
input  [31:0] bias_buf_2;
input  [31:0] bias_buf_1;
input  [31:0] bias_buf;
input  [9:0] empty;
input  [9:0] shl_ln;
output  [31:0] qp_mem_Addr_A;
output   qp_mem_EN_A;
output  [15:0] qp_mem_WEN_A;
output  [127:0] qp_mem_Din_A;
input  [127:0] qp_mem_Dout_A;
input  [4:0] oc_valid;
output  [7:0] nshift_buf_15_out;
output   nshift_buf_15_out_ap_vld;
output  [7:0] nshift_buf_14_out;
output   nshift_buf_14_out_ap_vld;
output  [7:0] nshift_buf_13_out;
output   nshift_buf_13_out_ap_vld;
output  [7:0] nshift_buf_12_out;
output   nshift_buf_12_out_ap_vld;
output  [7:0] nshift_buf_11_out;
output   nshift_buf_11_out_ap_vld;
output  [7:0] nshift_buf_10_out;
output   nshift_buf_10_out_ap_vld;
output  [7:0] nshift_buf_9_out;
output   nshift_buf_9_out_ap_vld;
output  [7:0] nshift_buf_8_out;
output   nshift_buf_8_out_ap_vld;
output  [31:0] m0_buf_15_out;
output   m0_buf_15_out_ap_vld;
output  [31:0] m0_buf_14_out;
output   m0_buf_14_out_ap_vld;
output  [31:0] m0_buf_13_out;
output   m0_buf_13_out_ap_vld;
output  [31:0] m0_buf_12_out;
output   m0_buf_12_out_ap_vld;
output  [31:0] m0_buf_11_out;
output   m0_buf_11_out_ap_vld;
output  [31:0] m0_buf_10_out;
output   m0_buf_10_out_ap_vld;
output  [31:0] m0_buf_9_out;
output   m0_buf_9_out_ap_vld;
output  [31:0] m0_buf_8_out;
output   m0_buf_8_out_ap_vld;
output  [31:0] bias_buf_15_out;
output   bias_buf_15_out_ap_vld;
output  [31:0] bias_buf_14_out;
output   bias_buf_14_out_ap_vld;
output  [31:0] bias_buf_13_out;
output   bias_buf_13_out_ap_vld;
output  [31:0] bias_buf_12_out;
output   bias_buf_12_out_ap_vld;
output  [31:0] bias_buf_11_out;
output   bias_buf_11_out_ap_vld;
output  [31:0] bias_buf_10_out;
output   bias_buf_10_out_ap_vld;
output  [31:0] bias_buf_9_out;
output   bias_buf_9_out_ap_vld;
output  [31:0] bias_buf_8_out;
output   bias_buf_8_out_ap_vld;

reg ap_idle;
reg nshift_buf_15_out_ap_vld;
reg nshift_buf_14_out_ap_vld;
reg nshift_buf_13_out_ap_vld;
reg nshift_buf_12_out_ap_vld;
reg nshift_buf_11_out_ap_vld;
reg nshift_buf_10_out_ap_vld;
reg nshift_buf_9_out_ap_vld;
reg nshift_buf_8_out_ap_vld;
reg m0_buf_15_out_ap_vld;
reg m0_buf_14_out_ap_vld;
reg m0_buf_13_out_ap_vld;
reg m0_buf_12_out_ap_vld;
reg m0_buf_11_out_ap_vld;
reg m0_buf_10_out_ap_vld;
reg m0_buf_9_out_ap_vld;
reg m0_buf_8_out_ap_vld;
reg bias_buf_15_out_ap_vld;
reg bias_buf_14_out_ap_vld;
reg bias_buf_13_out_ap_vld;
reg bias_buf_12_out_ap_vld;
reg bias_buf_11_out_ap_vld;
reg bias_buf_10_out_ap_vld;
reg bias_buf_9_out_ap_vld;
reg bias_buf_8_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln120_fu_758_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] trunc_ln120_fu_778_p1;
reg   [2:0] trunc_ln120_reg_1373;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln122_fu_783_p2;
reg   [0:0] icmp_ln122_reg_1377;
wire   [63:0] zext_ln123_fu_801_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] t_fu_170;
wire   [3:0] add_ln120_fu_764_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_t_1;
reg   [31:0] bias_buf_8_fu_174;
wire   [31:0] bias_buf_16_fu_931_p1;
reg   [31:0] bias_buf_9_fu_178;
reg   [31:0] bias_buf_10_fu_182;
reg   [31:0] bias_buf_11_fu_186;
reg   [31:0] bias_buf_12_fu_190;
reg   [31:0] bias_buf_13_fu_194;
reg   [31:0] bias_buf_14_fu_198;
reg   [31:0] bias_buf_15_fu_202;
reg   [31:0] m0_buf_8_fu_206;
reg   [31:0] m0_buf_9_fu_210;
reg   [31:0] m0_buf_10_fu_214;
reg   [31:0] m0_buf_11_fu_218;
reg   [31:0] m0_buf_12_fu_222;
reg   [31:0] m0_buf_13_fu_226;
reg   [31:0] m0_buf_14_fu_230;
reg   [31:0] m0_buf_15_fu_234;
reg   [7:0] nshift_buf_8_fu_238;
wire   [7:0] zext_ln126_fu_951_p1;
reg   [7:0] nshift_buf_9_fu_242;
reg   [7:0] nshift_buf_10_fu_246;
reg   [7:0] nshift_buf_11_fu_250;
reg   [7:0] nshift_buf_12_fu_254;
reg   [7:0] nshift_buf_13_fu_258;
reg   [7:0] nshift_buf_14_fu_262;
reg   [7:0] nshift_buf_15_fu_266;
wire    ap_block_pp0_stage0_01001;
reg    qp_mem_EN_A_local;
wire   [31:0] qp_mem_Addr_A_local;
wire   [31:0] qp_mem_Addr_A_orig;
wire   [4:0] zext_ln120_1_fu_774_p1;
wire   [9:0] zext_ln120_fu_770_p1;
wire   [9:0] add_ln123_fu_789_p2;
wire   [9:0] add_ln123_1_fu_795_p2;
wire   [71:0] bias_buf_16_fu_931_p0;
wire   [71:0] m0_buf_16_fu_935_p1;
wire   [71:0] nshift_buf_16_fu_943_p1;
wire   [5:0] nshift_buf_16_fu_943_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_432;
reg    ap_condition_436;
reg    ap_condition_439;
reg    ap_condition_442;
reg    ap_condition_445;
reg    ap_condition_448;
reg    ap_condition_451;
reg    ap_condition_454;
reg    ap_condition_457;
reg    ap_condition_460;
reg    ap_condition_463;
reg    ap_condition_466;
reg    ap_condition_469;
reg    ap_condition_472;
reg    ap_condition_475;
reg    ap_condition_478;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 t_fu_170 = 4'd0;
#0 bias_buf_8_fu_174 = 32'd0;
#0 bias_buf_9_fu_178 = 32'd0;
#0 bias_buf_10_fu_182 = 32'd0;
#0 bias_buf_11_fu_186 = 32'd0;
#0 bias_buf_12_fu_190 = 32'd0;
#0 bias_buf_13_fu_194 = 32'd0;
#0 bias_buf_14_fu_198 = 32'd0;
#0 bias_buf_15_fu_202 = 32'd0;
#0 m0_buf_8_fu_206 = 32'd0;
#0 m0_buf_9_fu_210 = 32'd0;
#0 m0_buf_10_fu_214 = 32'd0;
#0 m0_buf_11_fu_218 = 32'd0;
#0 m0_buf_12_fu_222 = 32'd0;
#0 m0_buf_13_fu_226 = 32'd0;
#0 m0_buf_14_fu_230 = 32'd0;
#0 m0_buf_15_fu_234 = 32'd0;
#0 nshift_buf_8_fu_238 = 8'd0;
#0 nshift_buf_9_fu_242 = 8'd0;
#0 nshift_buf_10_fu_246 = 8'd0;
#0 nshift_buf_11_fu_250 = 8'd0;
#0 nshift_buf_12_fu_254 = 8'd0;
#0 nshift_buf_13_fu_258 = 8'd0;
#0 nshift_buf_14_fu_262 = 8'd0;
#0 nshift_buf_15_fu_266 = 8'd0;
#0 ap_done_reg = 1'b0;
end

tinyissimo_layer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_10_fu_182 <= bias_buf_2;
        end else if ((1'b1 == ap_condition_436)) begin
            bias_buf_10_fu_182 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_432)) begin
            bias_buf_10_fu_182 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_11_fu_186 <= bias_buf_3;
        end else if ((1'b1 == ap_condition_442)) begin
            bias_buf_11_fu_186 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_439)) begin
            bias_buf_11_fu_186 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_12_fu_190 <= bias_buf_4;
        end else if ((1'b1 == ap_condition_448)) begin
            bias_buf_12_fu_190 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_445)) begin
            bias_buf_12_fu_190 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_13_fu_194 <= bias_buf_5;
        end else if ((1'b1 == ap_condition_454)) begin
            bias_buf_13_fu_194 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_451)) begin
            bias_buf_13_fu_194 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_14_fu_198 <= bias_buf_6;
        end else if ((1'b1 == ap_condition_460)) begin
            bias_buf_14_fu_198 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_457)) begin
            bias_buf_14_fu_198 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_15_fu_202 <= bias_buf_7;
        end else if ((1'b1 == ap_condition_466)) begin
            bias_buf_15_fu_202 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_463)) begin
            bias_buf_15_fu_202 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_8_fu_174 <= bias_buf;
        end else if ((1'b1 == ap_condition_472)) begin
            bias_buf_8_fu_174 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_469)) begin
            bias_buf_8_fu_174 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            bias_buf_9_fu_178 <= bias_buf_1;
        end else if ((1'b1 == ap_condition_478)) begin
            bias_buf_9_fu_178 <= bias_buf_16_fu_931_p1;
        end else if ((1'b1 == ap_condition_475)) begin
            bias_buf_9_fu_178 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_10_fu_214 <= m0_buf_2;
        end else if ((1'b1 == ap_condition_436)) begin
            m0_buf_10_fu_214 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_432)) begin
            m0_buf_10_fu_214 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_11_fu_218 <= m0_buf_3;
        end else if ((1'b1 == ap_condition_442)) begin
            m0_buf_11_fu_218 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_439)) begin
            m0_buf_11_fu_218 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_12_fu_222 <= m0_buf_4;
        end else if ((1'b1 == ap_condition_448)) begin
            m0_buf_12_fu_222 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_445)) begin
            m0_buf_12_fu_222 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_13_fu_226 <= m0_buf_5;
        end else if ((1'b1 == ap_condition_454)) begin
            m0_buf_13_fu_226 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_451)) begin
            m0_buf_13_fu_226 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_14_fu_230 <= m0_buf_6;
        end else if ((1'b1 == ap_condition_460)) begin
            m0_buf_14_fu_230 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_457)) begin
            m0_buf_14_fu_230 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_15_fu_234 <= m0_buf_7;
        end else if ((1'b1 == ap_condition_466)) begin
            m0_buf_15_fu_234 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_463)) begin
            m0_buf_15_fu_234 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_8_fu_206 <= m0_buf;
        end else if ((1'b1 == ap_condition_472)) begin
            m0_buf_8_fu_206 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_469)) begin
            m0_buf_8_fu_206 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            m0_buf_9_fu_210 <= m0_buf_1;
        end else if ((1'b1 == ap_condition_478)) begin
            m0_buf_9_fu_210 <= {{m0_buf_16_fu_935_p1[63:32]}};
        end else if ((1'b1 == ap_condition_475)) begin
            m0_buf_9_fu_210 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_10_fu_246 <= nshift_buf_2;
        end else if ((1'b1 == ap_condition_436)) begin
            nshift_buf_10_fu_246 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_432)) begin
            nshift_buf_10_fu_246 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_11_fu_250 <= nshift_buf_3;
        end else if ((1'b1 == ap_condition_442)) begin
            nshift_buf_11_fu_250 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_439)) begin
            nshift_buf_11_fu_250 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_12_fu_254 <= nshift_buf_4;
        end else if ((1'b1 == ap_condition_448)) begin
            nshift_buf_12_fu_254 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_445)) begin
            nshift_buf_12_fu_254 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_13_fu_258 <= nshift_buf_5;
        end else if ((1'b1 == ap_condition_454)) begin
            nshift_buf_13_fu_258 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_451)) begin
            nshift_buf_13_fu_258 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_14_fu_262 <= nshift_buf_6;
        end else if ((1'b1 == ap_condition_460)) begin
            nshift_buf_14_fu_262 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_457)) begin
            nshift_buf_14_fu_262 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_15_fu_266 <= nshift_buf_7;
        end else if ((1'b1 == ap_condition_466)) begin
            nshift_buf_15_fu_266 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_463)) begin
            nshift_buf_15_fu_266 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_8_fu_238 <= nshift_buf;
        end else if ((1'b1 == ap_condition_472)) begin
            nshift_buf_8_fu_238 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_469)) begin
            nshift_buf_8_fu_238 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            nshift_buf_9_fu_242 <= nshift_buf_1;
        end else if ((1'b1 == ap_condition_478)) begin
            nshift_buf_9_fu_242 <= zext_ln126_fu_951_p1;
        end else if ((1'b1 == ap_condition_475)) begin
            nshift_buf_9_fu_242 <= 8'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln120_fu_758_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_170 <= add_ln120_fu_764_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_170 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln122_reg_1377 <= icmp_ln122_fu_783_p2;
        trunc_ln120_reg_1373 <= trunc_ln120_fu_778_p1;
    end
end

always @ (*) begin
    if (((icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_170;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_10_out_ap_vld = 1'b1;
    end else begin
        bias_buf_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_11_out_ap_vld = 1'b1;
    end else begin
        bias_buf_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_12_out_ap_vld = 1'b1;
    end else begin
        bias_buf_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_13_out_ap_vld = 1'b1;
    end else begin
        bias_buf_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_14_out_ap_vld = 1'b1;
    end else begin
        bias_buf_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_15_out_ap_vld = 1'b1;
    end else begin
        bias_buf_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_8_out_ap_vld = 1'b1;
    end else begin
        bias_buf_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_buf_9_out_ap_vld = 1'b1;
    end else begin
        bias_buf_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_10_out_ap_vld = 1'b1;
    end else begin
        m0_buf_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_11_out_ap_vld = 1'b1;
    end else begin
        m0_buf_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_12_out_ap_vld = 1'b1;
    end else begin
        m0_buf_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_13_out_ap_vld = 1'b1;
    end else begin
        m0_buf_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_14_out_ap_vld = 1'b1;
    end else begin
        m0_buf_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_15_out_ap_vld = 1'b1;
    end else begin
        m0_buf_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_8_out_ap_vld = 1'b1;
    end else begin
        m0_buf_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m0_buf_9_out_ap_vld = 1'b1;
    end else begin
        m0_buf_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_10_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_11_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_12_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_13_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_14_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_15_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_8_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln120_fu_758_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nshift_buf_9_out_ap_vld = 1'b1;
    end else begin
        nshift_buf_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        qp_mem_EN_A_local = 1'b1;
    end else begin
        qp_mem_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln120_fu_764_p2 = (ap_sig_allocacmp_t_1 + 4'd1);

assign add_ln123_1_fu_795_p2 = (add_ln123_fu_789_p2 + shl_ln);

assign add_ln123_fu_789_p2 = (zext_ln120_fu_770_p1 + empty);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_432 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd2));
end

always @ (*) begin
    ap_condition_436 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd2));
end

always @ (*) begin
    ap_condition_439 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd3));
end

always @ (*) begin
    ap_condition_442 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd3));
end

always @ (*) begin
    ap_condition_445 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd4));
end

always @ (*) begin
    ap_condition_448 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd4));
end

always @ (*) begin
    ap_condition_451 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd5));
end

always @ (*) begin
    ap_condition_454 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd5));
end

always @ (*) begin
    ap_condition_457 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd6));
end

always @ (*) begin
    ap_condition_460 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd6));
end

always @ (*) begin
    ap_condition_463 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd7));
end

always @ (*) begin
    ap_condition_466 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd7));
end

always @ (*) begin
    ap_condition_469 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd0));
end

always @ (*) begin
    ap_condition_472 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd0));
end

always @ (*) begin
    ap_condition_475 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd0) & (trunc_ln120_reg_1373 == 3'd1));
end

always @ (*) begin
    ap_condition_478 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln122_reg_1377 == 1'd1) & (trunc_ln120_reg_1373 == 3'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bias_buf_10_out = bias_buf_10_fu_182;

assign bias_buf_11_out = bias_buf_11_fu_186;

assign bias_buf_12_out = bias_buf_12_fu_190;

assign bias_buf_13_out = bias_buf_13_fu_194;

assign bias_buf_14_out = bias_buf_14_fu_198;

assign bias_buf_15_out = bias_buf_15_fu_202;

assign bias_buf_16_fu_931_p0 = qp_mem_Dout_A;

assign bias_buf_16_fu_931_p1 = bias_buf_16_fu_931_p0[31:0];

assign bias_buf_8_out = bias_buf_8_fu_174;

assign bias_buf_9_out = bias_buf_9_fu_178;

assign icmp_ln120_fu_758_p2 = ((ap_sig_allocacmp_t_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_783_p2 = (($signed(zext_ln120_1_fu_774_p1) < $signed(oc_valid)) ? 1'b1 : 1'b0);

assign m0_buf_10_out = m0_buf_10_fu_214;

assign m0_buf_11_out = m0_buf_11_fu_218;

assign m0_buf_12_out = m0_buf_12_fu_222;

assign m0_buf_13_out = m0_buf_13_fu_226;

assign m0_buf_14_out = m0_buf_14_fu_230;

assign m0_buf_15_out = m0_buf_15_fu_234;

assign m0_buf_16_fu_935_p1 = qp_mem_Dout_A;

assign m0_buf_8_out = m0_buf_8_fu_206;

assign m0_buf_9_out = m0_buf_9_fu_210;

assign nshift_buf_10_out = nshift_buf_10_fu_246;

assign nshift_buf_11_out = nshift_buf_11_fu_250;

assign nshift_buf_12_out = nshift_buf_12_fu_254;

assign nshift_buf_13_out = nshift_buf_13_fu_258;

assign nshift_buf_14_out = nshift_buf_14_fu_262;

assign nshift_buf_15_out = nshift_buf_15_fu_266;

assign nshift_buf_16_fu_943_p1 = qp_mem_Dout_A;

assign nshift_buf_16_fu_943_p3 = {{nshift_buf_16_fu_943_p1[69:64]}};

assign nshift_buf_8_out = nshift_buf_8_fu_238;

assign nshift_buf_9_out = nshift_buf_9_fu_242;

assign qp_mem_Addr_A = qp_mem_Addr_A_local;

assign qp_mem_Addr_A_local = qp_mem_Addr_A_orig << 32'd4;

assign qp_mem_Addr_A_orig = zext_ln123_fu_801_p1;

assign qp_mem_Din_A = 128'd0;

assign qp_mem_EN_A = qp_mem_EN_A_local;

assign qp_mem_WEN_A = 16'd0;

assign trunc_ln120_fu_778_p1 = ap_sig_allocacmp_t_1[2:0];

assign zext_ln120_1_fu_774_p1 = ap_sig_allocacmp_t_1;

assign zext_ln120_fu_770_p1 = ap_sig_allocacmp_t_1;

assign zext_ln123_fu_801_p1 = add_ln123_1_fu_795_p2;

assign zext_ln126_fu_951_p1 = nshift_buf_16_fu_943_p3;

endmodule //tinyissimo_layer_top_tinyissimo_layer_top_Pipeline_LOAD_QP
