// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module tinyissimo_layer_top_partselect_32ns_128ns_7ns_32_1_1 (sel,din,dout);

parameter ADDRWIDTH = 7;
parameter DATAWIDTH = 128;
parameter DATA1WIDTH = 32;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
output [DATA1WIDTH-1:0] dout;

wire [DATAWIDTH+DATA1WIDTH-1:0] din_tmp;
wire [DATA1WIDTH-1:0] dout_tmp;




assign din_tmp = { 32'b00000000000000000000000000000000,din };

assign dout_tmp = din_tmp[sel+32-1 -: 32];




assign dout = dout_tmp;




endmodule
