// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module tinyissimo_layer_top_tinyissimo_layer_Pipeline_OUT_COL_STORE_pool_buf_63_RAM_2P_LUTRAM_1R1W (
    address0, ce0,
    q0,
    address1, ce1,
    d1, we1,
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 7;
parameter AddressRange = 128;

input [AddressWidth-1:0] address0;
input ce0;
output reg [DataWidth-1:0] q0;
input [AddressWidth-1:0] address1;
input ce1;
input [DataWidth-1:0] d1;
input we1;
input reset;
input clk;

(* ram_style = "distributed" *) reg [DataWidth-1:0] ram[0:AddressRange-1];


always @(posedge clk)
begin
    if (ce0)
    begin
        q0 <= ram[address0];
    end
end

always @(posedge clk)
begin
    if (ce1)
    begin
        if (we1)
            ram[address1] <= d1;
    end
end


endmodule

