// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_WT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        shl_ln,
        kw,
        ic_tiles,
        kh_cast38,
        wt_base,
        zext_ln190,
        w_buf_address1,
        w_buf_ce1,
        w_buf_we1,
        w_buf_d1,
        w_buf_1_address1,
        w_buf_1_ce1,
        w_buf_1_we1,
        w_buf_1_d1,
        w_buf_2_address1,
        w_buf_2_ce1,
        w_buf_2_we1,
        w_buf_2_d1,
        w_buf_3_address1,
        w_buf_3_ce1,
        w_buf_3_we1,
        w_buf_3_d1,
        w_buf_4_address1,
        w_buf_4_ce1,
        w_buf_4_we1,
        w_buf_4_d1,
        w_buf_5_address1,
        w_buf_5_ce1,
        w_buf_5_we1,
        w_buf_5_d1,
        w_buf_6_address1,
        w_buf_6_ce1,
        w_buf_6_we1,
        w_buf_6_d1,
        w_buf_7_address1,
        w_buf_7_ce1,
        w_buf_7_we1,
        w_buf_7_d1,
        w_buf_8_address1,
        w_buf_8_ce1,
        w_buf_8_we1,
        w_buf_8_d1,
        w_buf_9_address1,
        w_buf_9_ce1,
        w_buf_9_we1,
        w_buf_9_d1,
        w_buf_10_address1,
        w_buf_10_ce1,
        w_buf_10_we1,
        w_buf_10_d1,
        w_buf_11_address1,
        w_buf_11_ce1,
        w_buf_11_we1,
        w_buf_11_d1,
        w_buf_12_address1,
        w_buf_12_ce1,
        w_buf_12_we1,
        w_buf_12_d1,
        w_buf_13_address1,
        w_buf_13_ce1,
        w_buf_13_we1,
        w_buf_13_d1,
        w_buf_14_address1,
        w_buf_14_ce1,
        w_buf_14_we1,
        w_buf_14_d1,
        w_buf_15_address1,
        w_buf_15_ce1,
        w_buf_15_we1,
        w_buf_15_d1,
        wt_mem_Addr_A,
        wt_mem_EN_A,
        wt_mem_WEN_A,
        wt_mem_Din_A,
        wt_mem_Dout_A
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] shl_ln;
input  [1:0] kw;
input  [3:0] ic_tiles;
input  [1:0] kh_cast38;
input  [14:0] wt_base;
input  [12:0] zext_ln190;
output  [6:0] w_buf_address1;
output   w_buf_ce1;
output   w_buf_we1;
output  [127:0] w_buf_d1;
output  [6:0] w_buf_1_address1;
output   w_buf_1_ce1;
output   w_buf_1_we1;
output  [127:0] w_buf_1_d1;
output  [6:0] w_buf_2_address1;
output   w_buf_2_ce1;
output   w_buf_2_we1;
output  [127:0] w_buf_2_d1;
output  [6:0] w_buf_3_address1;
output   w_buf_3_ce1;
output   w_buf_3_we1;
output  [127:0] w_buf_3_d1;
output  [6:0] w_buf_4_address1;
output   w_buf_4_ce1;
output   w_buf_4_we1;
output  [127:0] w_buf_4_d1;
output  [6:0] w_buf_5_address1;
output   w_buf_5_ce1;
output   w_buf_5_we1;
output  [127:0] w_buf_5_d1;
output  [6:0] w_buf_6_address1;
output   w_buf_6_ce1;
output   w_buf_6_we1;
output  [127:0] w_buf_6_d1;
output  [6:0] w_buf_7_address1;
output   w_buf_7_ce1;
output   w_buf_7_we1;
output  [127:0] w_buf_7_d1;
output  [6:0] w_buf_8_address1;
output   w_buf_8_ce1;
output   w_buf_8_we1;
output  [127:0] w_buf_8_d1;
output  [6:0] w_buf_9_address1;
output   w_buf_9_ce1;
output   w_buf_9_we1;
output  [127:0] w_buf_9_d1;
output  [6:0] w_buf_10_address1;
output   w_buf_10_ce1;
output   w_buf_10_we1;
output  [127:0] w_buf_10_d1;
output  [6:0] w_buf_11_address1;
output   w_buf_11_ce1;
output   w_buf_11_we1;
output  [127:0] w_buf_11_d1;
output  [6:0] w_buf_12_address1;
output   w_buf_12_ce1;
output   w_buf_12_we1;
output  [127:0] w_buf_12_d1;
output  [6:0] w_buf_13_address1;
output   w_buf_13_ce1;
output   w_buf_13_we1;
output  [127:0] w_buf_13_d1;
output  [6:0] w_buf_14_address1;
output   w_buf_14_ce1;
output   w_buf_14_we1;
output  [127:0] w_buf_14_d1;
output  [6:0] w_buf_15_address1;
output   w_buf_15_ce1;
output   w_buf_15_we1;
output  [127:0] w_buf_15_d1;
output  [31:0] wt_mem_Addr_A;
output   wt_mem_EN_A;
output  [15:0] wt_mem_WEN_A;
output  [127:0] wt_mem_Din_A;
input  [127:0] wt_mem_Dout_A;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln190_fu_557_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] zext_ln190_cast_fu_501_p1;
reg   [14:0] zext_ln190_cast_reg_897;
wire   [31:0] kh_cast38_cast_fu_505_p1;
reg   [31:0] kh_cast38_cast_reg_902;
wire   [31:0] kw_cast39157_fu_509_p1;
reg   [31:0] kw_cast39157_reg_907;
wire   [31:0] zext_ln88_fu_513_p1;
reg   [31:0] zext_ln88_reg_912;
reg   [31:0] wt_t_3_reg_917;
wire   [6:0] add_ln194_3_fu_635_p2;
reg   [6:0] add_ln194_3_reg_924;
wire   [63:0] zext_ln194_fu_582_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln194_1_fu_833_p1;
reg   [31:0] wt_t_fu_144;
wire   [31:0] wt_t_2_fu_744_p3;
wire    ap_loop_init;
reg   [31:0] wt_ict_fu_148;
wire   [31:0] wt_ict_3_fu_752_p3;
reg   [31:0] wt_kh_fu_152;
wire   [31:0] wt_kh_2_fu_780_p9;
reg   [31:0] wt_kw_fu_156;
wire   [31:0] wt_kw_1_fu_800_p3;
reg   [10:0] i_1_fu_160;
wire   [10:0] add_ln190_fu_562_p2;
reg    wt_mem_EN_A_local;
wire   [31:0] wt_mem_Addr_A_local;
wire   [31:0] wt_mem_Addr_A_orig;
reg    w_buf_15_we1_local;
reg    w_buf_15_ce1_local;
reg    w_buf_14_we1_local;
reg    w_buf_14_ce1_local;
reg    w_buf_13_we1_local;
reg    w_buf_13_ce1_local;
reg    w_buf_12_we1_local;
reg    w_buf_12_ce1_local;
reg    w_buf_11_we1_local;
reg    w_buf_11_ce1_local;
reg    w_buf_10_we1_local;
reg    w_buf_10_ce1_local;
reg    w_buf_9_we1_local;
reg    w_buf_9_ce1_local;
reg    w_buf_8_we1_local;
reg    w_buf_8_ce1_local;
reg    w_buf_7_we1_local;
reg    w_buf_7_ce1_local;
reg    w_buf_6_we1_local;
reg    w_buf_6_ce1_local;
reg    w_buf_5_we1_local;
reg    w_buf_5_ce1_local;
reg    w_buf_4_we1_local;
reg    w_buf_4_ce1_local;
reg    w_buf_3_we1_local;
reg    w_buf_3_ce1_local;
reg    w_buf_2_we1_local;
reg    w_buf_2_ce1_local;
reg    w_buf_1_we1_local;
reg    w_buf_1_ce1_local;
reg    w_buf_we1_local;
reg    w_buf_ce1_local;
wire   [14:0] zext_ln190_1_fu_568_p1;
wire   [14:0] add_ln194_1_fu_572_p2;
wire   [14:0] add_ln194_fu_577_p2;
wire   [4:0] trunc_ln194_1_fu_591_p1;
wire   [6:0] p_shl_fu_595_p3;
wire   [6:0] trunc_ln194_fu_587_p1;
wire   [6:0] sub_ln194_fu_603_p2;
wire   [6:0] trunc_ln194_2_fu_609_p1;
wire   [6:0] add_ln194_2_fu_613_p2;
wire   [6:0] shl_ln194_fu_619_p2;
wire   [6:0] sub_ln194_1_fu_625_p2;
wire   [6:0] trunc_ln194_3_fu_631_p1;
wire   [31:0] wt_kw_4_fu_677_p2;
wire   [31:0] wt_kh_4_fu_688_p2;
wire   [31:0] wt_ict_5_fu_699_p2;
wire   [0:0] icmp_ln201_fu_705_p2;
wire   [0:0] xor_ln201_fu_710_p2;
wire   [31:0] add_ln203_fu_716_p2;
wire   [0:0] icmp_ln197_fu_683_p2;
wire   [0:0] icmp_ln199_fu_694_p2;
wire   [0:0] or_ln199_fu_738_p2;
wire   [31:0] wt_t_4_fu_722_p3;
wire   [31:0] wt_ict_6_fu_730_p3;
wire   [0:0] xor_ln197_fu_760_p2;
wire   [0:0] and_ln199_fu_766_p2;
wire   [31:0] wt_kh_2_fu_780_p7;
wire   [1:0] wt_kh_2_fu_780_p8;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] wt_kh_2_fu_780_p1;
wire   [1:0] wt_kh_2_fu_780_p3;
wire   [1:0] wt_kh_2_fu_780_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 wt_t_fu_144 = 32'd0;
#0 wt_ict_fu_148 = 32'd0;
#0 wt_kh_fu_152 = 32'd0;
#0 wt_kw_fu_156 = 32'd0;
#0 i_1_fu_160 = 11'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) tinyissimo_layer_top_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U357(
    .din0(wt_kh_fu_152),
    .din1(wt_kh_4_fu_688_p2),
    .din2(32'd0),
    .def(wt_kh_2_fu_780_p7),
    .sel(wt_kh_2_fu_780_p8),
    .dout(wt_kh_2_fu_780_p9)
);

tinyissimo_layer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_160 <= 11'd0;
        end else if (((icmp_ln190_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_1_fu_160 <= add_ln190_fu_562_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            wt_ict_fu_148 <= 32'd0;
        end else if (((icmp_ln190_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            wt_ict_fu_148 <= wt_ict_3_fu_752_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            wt_kh_fu_152 <= 32'd0;
        end else if (((icmp_ln190_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            wt_kh_fu_152 <= wt_kh_2_fu_780_p9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            wt_kw_fu_156 <= 32'd0;
        end else if (((icmp_ln190_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            wt_kw_fu_156 <= wt_kw_1_fu_800_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            wt_t_fu_144 <= 32'd0;
        end else if (((icmp_ln190_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            wt_t_fu_144 <= wt_t_2_fu_744_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln194_3_reg_924 <= add_ln194_3_fu_635_p2;
        kh_cast38_cast_reg_902[1 : 0] <= kh_cast38_cast_fu_505_p1[1 : 0];
        kw_cast39157_reg_907[1 : 0] <= kw_cast39157_fu_509_p1[1 : 0];
        wt_t_3_reg_917 <= wt_t_fu_144;
        zext_ln190_cast_reg_897[12 : 0] <= zext_ln190_cast_fu_501_p1[12 : 0];
        zext_ln88_reg_912[3 : 0] <= zext_ln88_fu_513_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln190_fu_557_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_10_ce1_local = 1'b1;
    end else begin
        w_buf_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd10))) begin
        w_buf_10_we1_local = 1'b1;
    end else begin
        w_buf_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_11_ce1_local = 1'b1;
    end else begin
        w_buf_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd11))) begin
        w_buf_11_we1_local = 1'b1;
    end else begin
        w_buf_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_12_ce1_local = 1'b1;
    end else begin
        w_buf_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd12))) begin
        w_buf_12_we1_local = 1'b1;
    end else begin
        w_buf_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_13_ce1_local = 1'b1;
    end else begin
        w_buf_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd13))) begin
        w_buf_13_we1_local = 1'b1;
    end else begin
        w_buf_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_14_ce1_local = 1'b1;
    end else begin
        w_buf_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd14))) begin
        w_buf_14_we1_local = 1'b1;
    end else begin
        w_buf_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_15_ce1_local = 1'b1;
    end else begin
        w_buf_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd15))) begin
        w_buf_15_we1_local = 1'b1;
    end else begin
        w_buf_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_1_ce1_local = 1'b1;
    end else begin
        w_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd1))) begin
        w_buf_1_we1_local = 1'b1;
    end else begin
        w_buf_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_2_ce1_local = 1'b1;
    end else begin
        w_buf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd2))) begin
        w_buf_2_we1_local = 1'b1;
    end else begin
        w_buf_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_3_ce1_local = 1'b1;
    end else begin
        w_buf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd3))) begin
        w_buf_3_we1_local = 1'b1;
    end else begin
        w_buf_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_4_ce1_local = 1'b1;
    end else begin
        w_buf_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd4))) begin
        w_buf_4_we1_local = 1'b1;
    end else begin
        w_buf_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_5_ce1_local = 1'b1;
    end else begin
        w_buf_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd5))) begin
        w_buf_5_we1_local = 1'b1;
    end else begin
        w_buf_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_6_ce1_local = 1'b1;
    end else begin
        w_buf_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd6))) begin
        w_buf_6_we1_local = 1'b1;
    end else begin
        w_buf_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_7_ce1_local = 1'b1;
    end else begin
        w_buf_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd7))) begin
        w_buf_7_we1_local = 1'b1;
    end else begin
        w_buf_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_8_ce1_local = 1'b1;
    end else begin
        w_buf_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd8))) begin
        w_buf_8_we1_local = 1'b1;
    end else begin
        w_buf_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_9_ce1_local = 1'b1;
    end else begin
        w_buf_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd9))) begin
        w_buf_9_we1_local = 1'b1;
    end else begin
        w_buf_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w_buf_ce1_local = 1'b1;
    end else begin
        w_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (wt_t_3_reg_917 == 32'd0))) begin
        w_buf_we1_local = 1'b1;
    end else begin
        w_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wt_mem_EN_A_local = 1'b1;
    end else begin
        wt_mem_EN_A_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln190_fu_562_p2 = (i_1_fu_160 + 11'd1);

assign add_ln194_1_fu_572_p2 = (zext_ln190_1_fu_568_p1 + wt_base);

assign add_ln194_2_fu_613_p2 = (sub_ln194_fu_603_p2 + trunc_ln194_2_fu_609_p1);

assign add_ln194_3_fu_635_p2 = (sub_ln194_1_fu_625_p2 + trunc_ln194_3_fu_631_p1);

assign add_ln194_fu_577_p2 = (add_ln194_1_fu_572_p2 + zext_ln190_cast_reg_897);

assign add_ln203_fu_716_p2 = (wt_t_fu_144 + 32'd1);

assign and_ln199_fu_766_p2 = (xor_ln197_fu_760_p2 & icmp_ln199_fu_694_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln190_fu_557_p2 = ((i_1_fu_160 == shl_ln) ? 1'b1 : 1'b0);

assign icmp_ln197_fu_683_p2 = (($signed(wt_kw_4_fu_677_p2) < $signed(kw_cast39157_reg_907)) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_694_p2 = (($signed(wt_kh_4_fu_688_p2) < $signed(kh_cast38_cast_reg_902)) ? 1'b1 : 1'b0);

assign icmp_ln201_fu_705_p2 = (($signed(wt_ict_5_fu_699_p2) < $signed(zext_ln88_reg_912)) ? 1'b1 : 1'b0);

assign kh_cast38_cast_fu_505_p1 = kh_cast38;

assign kw_cast39157_fu_509_p1 = kw;

assign or_ln199_fu_738_p2 = (icmp_ln199_fu_694_p2 | icmp_ln197_fu_683_p2);

assign p_shl_fu_595_p3 = {{trunc_ln194_1_fu_591_p1}, {2'd0}};

assign shl_ln194_fu_619_p2 = add_ln194_2_fu_613_p2 << 7'd2;

assign sub_ln194_1_fu_625_p2 = (shl_ln194_fu_619_p2 - add_ln194_2_fu_613_p2);

assign sub_ln194_fu_603_p2 = (p_shl_fu_595_p3 - trunc_ln194_fu_587_p1);

assign trunc_ln194_1_fu_591_p1 = wt_ict_fu_148[4:0];

assign trunc_ln194_2_fu_609_p1 = wt_kh_fu_152[6:0];

assign trunc_ln194_3_fu_631_p1 = wt_kw_fu_156[6:0];

assign trunc_ln194_fu_587_p1 = wt_ict_fu_148[6:0];

assign w_buf_10_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_10_ce1 = w_buf_10_ce1_local;

assign w_buf_10_d1 = wt_mem_Dout_A;

assign w_buf_10_we1 = w_buf_10_we1_local;

assign w_buf_11_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_11_ce1 = w_buf_11_ce1_local;

assign w_buf_11_d1 = wt_mem_Dout_A;

assign w_buf_11_we1 = w_buf_11_we1_local;

assign w_buf_12_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_12_ce1 = w_buf_12_ce1_local;

assign w_buf_12_d1 = wt_mem_Dout_A;

assign w_buf_12_we1 = w_buf_12_we1_local;

assign w_buf_13_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_13_ce1 = w_buf_13_ce1_local;

assign w_buf_13_d1 = wt_mem_Dout_A;

assign w_buf_13_we1 = w_buf_13_we1_local;

assign w_buf_14_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_14_ce1 = w_buf_14_ce1_local;

assign w_buf_14_d1 = wt_mem_Dout_A;

assign w_buf_14_we1 = w_buf_14_we1_local;

assign w_buf_15_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_15_ce1 = w_buf_15_ce1_local;

assign w_buf_15_d1 = wt_mem_Dout_A;

assign w_buf_15_we1 = w_buf_15_we1_local;

assign w_buf_1_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_1_ce1 = w_buf_1_ce1_local;

assign w_buf_1_d1 = wt_mem_Dout_A;

assign w_buf_1_we1 = w_buf_1_we1_local;

assign w_buf_2_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_2_ce1 = w_buf_2_ce1_local;

assign w_buf_2_d1 = wt_mem_Dout_A;

assign w_buf_2_we1 = w_buf_2_we1_local;

assign w_buf_3_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_3_ce1 = w_buf_3_ce1_local;

assign w_buf_3_d1 = wt_mem_Dout_A;

assign w_buf_3_we1 = w_buf_3_we1_local;

assign w_buf_4_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_4_ce1 = w_buf_4_ce1_local;

assign w_buf_4_d1 = wt_mem_Dout_A;

assign w_buf_4_we1 = w_buf_4_we1_local;

assign w_buf_5_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_5_ce1 = w_buf_5_ce1_local;

assign w_buf_5_d1 = wt_mem_Dout_A;

assign w_buf_5_we1 = w_buf_5_we1_local;

assign w_buf_6_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_6_ce1 = w_buf_6_ce1_local;

assign w_buf_6_d1 = wt_mem_Dout_A;

assign w_buf_6_we1 = w_buf_6_we1_local;

assign w_buf_7_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_7_ce1 = w_buf_7_ce1_local;

assign w_buf_7_d1 = wt_mem_Dout_A;

assign w_buf_7_we1 = w_buf_7_we1_local;

assign w_buf_8_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_8_ce1 = w_buf_8_ce1_local;

assign w_buf_8_d1 = wt_mem_Dout_A;

assign w_buf_8_we1 = w_buf_8_we1_local;

assign w_buf_9_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_9_ce1 = w_buf_9_ce1_local;

assign w_buf_9_d1 = wt_mem_Dout_A;

assign w_buf_9_we1 = w_buf_9_we1_local;

assign w_buf_address1 = zext_ln194_1_fu_833_p1;

assign w_buf_ce1 = w_buf_ce1_local;

assign w_buf_d1 = wt_mem_Dout_A;

assign w_buf_we1 = w_buf_we1_local;

assign wt_ict_3_fu_752_p3 = ((or_ln199_fu_738_p2[0:0] == 1'b1) ? wt_ict_fu_148 : wt_ict_6_fu_730_p3);

assign wt_ict_5_fu_699_p2 = (wt_ict_fu_148 + 32'd1);

assign wt_ict_6_fu_730_p3 = ((xor_ln201_fu_710_p2[0:0] == 1'b1) ? 32'd0 : wt_ict_5_fu_699_p2);

assign wt_kh_2_fu_780_p7 = 'bx;

assign wt_kh_2_fu_780_p8 = {{icmp_ln197_fu_683_p2}, {and_ln199_fu_766_p2}};

assign wt_kh_4_fu_688_p2 = (wt_kh_fu_152 + 32'd1);

assign wt_kw_1_fu_800_p3 = ((icmp_ln197_fu_683_p2[0:0] == 1'b1) ? wt_kw_4_fu_677_p2 : 32'd0);

assign wt_kw_4_fu_677_p2 = (wt_kw_fu_156 + 32'd1);

assign wt_mem_Addr_A = wt_mem_Addr_A_local;

assign wt_mem_Addr_A_local = wt_mem_Addr_A_orig << 32'd4;

assign wt_mem_Addr_A_orig = zext_ln194_fu_582_p1;

assign wt_mem_Din_A = 128'd0;

assign wt_mem_EN_A = wt_mem_EN_A_local;

assign wt_mem_WEN_A = 16'd0;

assign wt_t_2_fu_744_p3 = ((or_ln199_fu_738_p2[0:0] == 1'b1) ? wt_t_fu_144 : wt_t_4_fu_722_p3);

assign wt_t_4_fu_722_p3 = ((xor_ln201_fu_710_p2[0:0] == 1'b1) ? add_ln203_fu_716_p2 : wt_t_fu_144);

assign xor_ln197_fu_760_p2 = (icmp_ln197_fu_683_p2 ^ 1'd1);

assign xor_ln201_fu_710_p2 = (icmp_ln201_fu_705_p2 ^ 1'd1);

assign zext_ln190_1_fu_568_p1 = i_1_fu_160;

assign zext_ln190_cast_fu_501_p1 = zext_ln190;

assign zext_ln194_1_fu_833_p1 = add_ln194_3_reg_924;

assign zext_ln194_fu_582_p1 = add_ln194_fu_577_p2;

assign zext_ln88_fu_513_p1 = ic_tiles;

always @ (posedge ap_clk) begin
    zext_ln190_cast_reg_897[14:13] <= 2'b00;
    kh_cast38_cast_reg_902[31:2] <= 30'b000000000000000000000000000000;
    kw_cast39157_reg_907[31:2] <= 30'b000000000000000000000000000000;
    zext_ln88_reg_912[31:4] <= 28'b0000000000000000000000000000;
end

endmodule //tinyissimo_layer_top_tinyissimo_layer_Pipeline_LOAD_WT
