// Stub file to satisfy a stale source-list reference in
// hardware/vivado/tinyissimoyolo/tinyissimoyolo.xpr (line 116, FileSet
// "sources_1"). The actual top of the synth is `playground_wrapper`
// (auto-generated by the BD at hardware/vivado/.../bd/playground/hdl/
// playground_wrapper.v), not this file.
//
// Removing the xpr reference is the proper fix but is fragile because
// Vivado re-saves the xpr on every project open. Until that's cleaned
// up, this empty module satisfies the file-existence check without
// affecting synthesis output.
//
// The "TopModule" property of the source set is "top" — Vivado uses
// this for elaboration/auto-detection but the actual run uses
// playground_wrapper. Defining `top` here as an empty module avoids
// any "module not found" errors during dependency analysis.

`timescale 1ns / 1ps

module top ();
endmodule
