#!/usr/bin/env python3
"""Generate a device tree overlay (.dts/.dtbo) from a Vivado .hwh file.

Parses the .hwh XML to produce proper device tree nodes for kernel-managed
PL IPs (e.g. AXI IIC) that PYNQ's auto-generated overlay misses.
"""

import argparse
import re
import subprocess
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree

# ZynqMP pl_ps_irq0 starts at SPI 89
ZYNQMP_PL_IRQ0_SPI_BASE = 89

# Maps IP MODTYPE to device tree properties.
# Add entries here when new kernel-managed IPs are needed.
KERNEL_DRIVER_IPS = {
    "axi_iic": {
        "compatible": ["xlnx,xps-iic-2.00.a", "xlnx,axi-iic-2.1"],
        "extra_props": {"#address-cells": 1, "#size-cells": 0},
    },
}

DTS_HEADER = """\
/*
 * Auto-generated device tree overlay for PL IP kernel drivers.
 * Source: {hwh_name}
 *
 * Generated by: scripts/generate-dtbo.py
 *
 * ZOCL and AFI nodes are NOT included here — they are provided by
 * pynq.dtbo (loaded at boot via pynq-dtbo.service).  This overlay
 * only adds nodes for kernel-managed PL IPs (e.g. AXI IIC).
 */

/dts-v1/;
/plugin/;

&amba {{
"""

DTS_FOOTER = "};\n"


def parse_hwh(hwh_path):
    tree = ElementTree.parse(hwh_path)
    return tree.getroot()


def extract_hwh_from_xsa(xsa_path):
    with zipfile.ZipFile(xsa_path, "r") as zf:
        hwh_files = [n for n in zf.namelist() if n.endswith(".hwh")]
        if not hwh_files:
            sys.exit(f"Error: no .hwh found inside {xsa_path}")
        # Shortest name is the top-level .hwh
        hwh_name = min(hwh_files, key=len)
        tmp_dir = Path(xsa_path).parent
        zf.extract(hwh_name, tmp_dir)
        return tmp_dir / hwh_name


def get_modules(root):
    modules = {}
    for mod in root.iter("MODULE"):
        instance = mod.get("INSTANCE")
        modtype = mod.get("MODTYPE")
        if instance and modtype:
            modules[instance] = {"element": mod, "modtype": modtype}
    return modules


def get_param(mod_element, name):
    for param in mod_element.iter("PARAMETER"):
        if param.get("NAME") == name:
            return param.get("VALUE")
    return None


def build_interrupt_map(modules):
    """Build {signal_name: concat_input_index} from the xlconcat module."""
    irq_map = {}
    for info in modules.values():
        if "xlconcat" not in info["modtype"]:
            continue
        for port in info["element"].iter("PORT"):
            name = port.get("NAME", "")
            match = re.match(r"^In(\d+)$", name)
            if not match:
                continue
            signame = port.get("SIGNAME")
            if signame:
                irq_map[signame] = int(match.group(1))
    return irq_map


def find_irq_signame(mod_element):
    """Find the interrupt output signal name from a module."""
    for port in mod_element.iter("PORT"):
        if port.get("SIGIS") == "INTERRUPT" and port.get("DIR") == "O":
            return port.get("SIGNAME")
    return None


def generate_node(instance, mod_element, driver_info, irq_map):
    baseaddr = get_param(mod_element, "C_BASEADDR")
    highaddr = get_param(mod_element, "C_HIGHADDR")
    if not baseaddr or not highaddr:
        print(f"Warning: {instance} missing C_BASEADDR/C_HIGHADDR, skipping", file=sys.stderr)
        return None

    base = int(baseaddr, 16)
    high = int(highaddr, 16)
    size = high - base + 1

    # reg property: <addr_hi addr_lo size_hi size_lo>
    # Kria KV260 axi bus has #address-cells=2, #size-cells=2
    addr_hi = (base >> 32) & 0xFFFFFFFF
    addr_lo = base & 0xFFFFFFFF
    size_hi = (size >> 32) & 0xFFFFFFFF
    size_lo = size & 0xFFFFFFFF

    compatible = ", ".join(f'"{c}"' for c in driver_info["compatible"])

    # Determine DT node name from IP type
    dt_type_map = {"axi_iic": "i2c"}
    dt_type = dt_type_map.get(driver_info.get("_modtype", ""), instance)
    node_name = f"{dt_type}@{base:x}"

    lines = []
    lines.append(f"    {instance}: {node_name} {{")
    lines.append(f"        compatible = {compatible};")
    lines.append(f"        reg = <0x{addr_hi:x} 0x{addr_lo:x} 0x{size_hi:x} 0x{size_lo:x}>;")

    # Interrupt
    irq_sig = find_irq_signame(mod_element)
    if irq_sig and irq_sig in irq_map:
        spi_num = ZYNQMP_PL_IRQ0_SPI_BASE + irq_map[irq_sig]
        lines.append("        interrupt-parent = <&gic>;")
        lines.append(f"        interrupts = <0 {spi_num} 4>;")

    lines.append("        clocks = <&zynqmp_clk 71>;")

    for prop, val in driver_info.get("extra_props", {}).items():
        lines.append(f"        {prop} = <{val}>;")

    lines.append("    };")

    return "\n".join(lines)


def generate_dts(hwh_path):
    root = parse_hwh(hwh_path)
    modules = get_modules(root)
    irq_map = build_interrupt_map(modules)

    nodes = []
    for instance, info in sorted(modules.items()):
        modtype = info["modtype"]
        if modtype not in KERNEL_DRIVER_IPS:
            continue
        driver_info = dict(KERNEL_DRIVER_IPS[modtype])
        driver_info["_modtype"] = modtype
        node = generate_node(instance, info["element"], driver_info, irq_map)
        if node:
            nodes.append(node)

    if not nodes:
        print("Warning: no kernel-managed IPs found in .hwh", file=sys.stderr)

    # Print interrupt mapping as a comment
    irq_comments = []
    for sig, idx in sorted(irq_map.items(), key=lambda x: x[1]):
        spi = ZYNQMP_PL_IRQ0_SPI_BASE + idx
        irq_comments.append(f" *   In{idx} = {sig} -> SPI {spi}")
    irq_block = ""
    if irq_comments:
        irq_block = "\n/*\n * Interrupt mapping (xlconcat -> pl_ps_irq0):\n"
        irq_block += "\n".join(irq_comments)
        irq_block += "\n */\n"

    hwh_name = Path(hwh_path).name
    dts = DTS_HEADER.format(hwh_name=hwh_name)
    dts += irq_block
    for node in nodes:
        dts += "\n" + node + "\n"
    dts += DTS_FOOTER

    return dts


def compile_dtbo(dts_path, dtbo_path):
    try:
        result = subprocess.run(
            ["dtc", "-@", "-I", "dts", "-O", "dtb", "-o", str(dtbo_path), str(dts_path)],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        sys.exit("Error: dtc not found in PATH. Install device-tree-compiler.")

    # dtc prints warnings to stderr even on success; only fail on actual errors
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(f"Error: dtc failed with exit code {result.returncode}")

    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)

    print(f"Compiled: {dtbo_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate device tree overlay from Vivado .hwh file",
    )
    parser.add_argument("hwh_file", help="Path to .hwh (or .xsa) file")
    parser.add_argument("-o", "--output", help="Output .dts path (default: same dir/basename as input)")
    parser.add_argument("--compile", action="store_true", help="Also compile to .dtbo using dtc")
    args = parser.parse_args()

    hwh_path = Path(args.hwh_file)
    if not hwh_path.exists():
        sys.exit(f"Error: file not found: {hwh_path}")

    # Handle .xsa input
    if hwh_path.suffix == ".xsa":
        print(f"Extracting .hwh from {hwh_path}...")
        hwh_path = extract_hwh_from_xsa(hwh_path)

    if args.output:
        dts_path = Path(args.output)
    else:
        dts_path = hwh_path.with_suffix(".dts")

    dts_content = generate_dts(hwh_path)

    dts_path.write_text(dts_content)
    print(f"Generated: {dts_path}")

    if args.compile:
        dtbo_path = dts_path.with_suffix(".dtbo")
        compile_dtbo(dts_path, dtbo_path)


if __name__ == "__main__":
    main()
